### ISSUE TITLE
[Microsoft Teams]...

### ISSUE THREAD

**Issue by stichingsd-vitrion** [raycast/extensions#10104]
### Extension

https://raycast.com/sven/microsoft-teams

#### Error:
```
Error: Invalid authorization URL
    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)
    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)
    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)
    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)
    at process.processImmediate (node:internal/timers:478:21)
```

### Steps To Reproduce

Install teams and connect

**Comment by svenwiegand** [comment]
@stichingsd-vitrion: Ensure, that you've completely followed the setup as described in the [documentation](https://www.raycast.com/sven/microsoft-teams), even including the admin part.
