### ISSUE TITLE
[Spotify Player]...

### ISSUE THREAD

**Issue by apoorv12** [raycast/extensions#10171]
### Extension

https://raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Player command failed: Premium required
    at Bn (/Users/apoorvkhandelwal/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/search.js:61:118)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n (/Users/apoorvkhandelwal/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/search.js:61:493)
```

### Steps To Reproduce

1. Install Spotify extension
2. Click to search
3. It redirects to spotify webpage for permission.
4. After giving permission, when search a song and tried to play.
5. It shows error.

**Comment by jatindotdev** [comment]
hey @apoorv12 

ig its mentioned on the extension website, the spotify apis need spotify premium account so we can access so the extension doesn't work without premium 🥲

**Comment by jatindotdev** [comment]
@raycastbot close this issue
