### ISSUE TITLE
[GitHub] Error loading my pull requests

### ISSUE THREAD

**Issue by tom-sherman** [raycast/extensions#10278]
### Extension

https://www.raycast.com/raycast/github

### Description

There is an API error when trying to load "My Pull Requests"

```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `E0D8:26CFC0:87D61F8:89BA07B:65AE5F22` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `E0D8:26CFC0:87D61F8:89BA07B:65AE5F22` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query myPullRequests($createdOpenQuery: String!, $createdClosedQuery: String!, $assignedOpenQuery: String!, $assignedClosedQuery: String!, $mentionedOpenQuery: String!, $mentionedClosedQuery: String!, $reviewRequestsOpenQuery: String!, $reviewRequestsClosedQuery: String!, $reviewedByOpenQuery: String!, $reviewedByClosedQuery: String!, $numberOfOpenItems: Int!, $numberOfClosedItems: Int!) {\n  createdOpen: search(\n    query: $createdOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  createdClosed: search(\n    query: $createdClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  assignedOpen: search(\n    query: $assignedOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  assignedClosed: search(\n    query: $assignedClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  mentionedOpen: search(\n    query: $mentionedOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  mentionedClosed: search(\n    query: $mentionedClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewRequestsOpen: search(\n    query: $reviewRequestsOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewRequestsClosed: search(\n    query: $reviewRequestsClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewedByOpen: search(\n    query: $reviewedByOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewedByClosed: search(\n    query: $reviewedByClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n}\n\nfragment PullRequestFields on PullRequest {\n  id\n  title\n  permalink\n  merged\n  number\n  isDraft\n  closed\n  updatedAt\n  mergeable\n  milestone {\n    id\n    title\n  }\n  reviewDecision\n  repository {\n    ...ShortRepositoryFields\n  }\n  headRefName\n  headRef {\n    name\n  }\n  author {\n    ...AuthorFields\n  }\n  comments(first: 0) {\n    totalCount\n  }\n  reviewThreads(first: 100) {\n    totalCount\n    nodes {\n      comments(first: 0) {\n        totalCount\n      }\n    }\n  }\n  reviews(first: 100) {\n    totalCount\n    nodes {\n      bodyText\n    }\n  }\n  commits(last: 1) {\n    nodes {\n      commit {\n        statusCheckRollup {\n          state\n        }\n      }\n    }\n  }\n  assignees(first: 50) {\n    totalCount\n    nodes {\n      ... on User {\n        ...UserFields\n      }\n    }\n  }\n}\n\nfragment ShortRepositoryFields on Repository {\n  id\n  defaultBranchRef {\n    target {\n      oid\n    }\n  }\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n}\n\nfragment AuthorFields on Actor {\n  ... on Bot {\n    id\n    login\n    avatarUrl(size: 64)\n  }\n  ... on User {\n    ...UserFields\n  }\n  ... on Mannequin {\n    id\n    login\n    avatarUrl(size: 64)\n  }\n  ... on Organization {\n    id\n    login\n    name\n    avatarUrl(size: 64)\n  }\n  ... on EnterpriseUserAccount {\n    id\n    login\n    name\n    avatarUrl(size: 64)\n  }\n}\n\nfragment UserFields on User {\n  id\n  avatarUrl\n  name\n  login\n  isViewer\n}","variables":{"createdOpenQuery":"is:pr author:@me archived:false is:open updated:>2024-01-08 ","createdClosedQuery":"is:pr author:@me archived:false is:closed updated:>2024-01-08 ","assignedOpenQuery":"is:pr assignee:@me archived:false is:open updated:>2024-01-08 ","assignedClosedQuery":"is:pr assignee:@me archived:false is:closed updated:>2024-01-08 ","mentionedOpenQuery":"is:pr mentions:@me archived:false is:open updated:>2024-01-08 ","mentionedClosedQuery":"is:pr mentions:@me archived:false is:closed updated:>2024-01-08 ","reviewRequestsOpenQuery":"is:pr review-requested:@me archived:false is:open updated:>2024-01-08 ","reviewRequestsClosedQuery":"is:pr review-requested:@me archived:false is:closed updated:>2024-01-08 ","reviewedByOpenQuery":"is:pr reviewed-by:@me archived:false is:open updated:>2024-01-08 ","reviewedByClosedQuery":"is:pr reviewed-by:@me archived:false is:closed updated:>2024-01-08 ","numberOfOpenItems":20,"numberOfClosedItems":20}}}
    at /Users/tom.sherman/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:49846
    at p (/Users/tom.sherman/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:43252)
    at Object.next (/Users/tom.sherman/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:42556)
    at u (/Users/tom.sherman/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:42114)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. Activate the pull request commaind

### Current Behaviour

Should load pull requests

### Expected Behaviour

There is an error in the API response from the GitHub API

**Comment by tom-sherman** [comment]
I tried the same query in the graphql explorer and get an Error 500

<img width="2078" alt="image" src="https://github.com/raycast/extensions/assets/9257001/866faf0f-1f7b-4f3a-9615-d23e6a311224">

**Comment by thomaslombart** [comment]
Do you have a lot of data in your pull requests (lots of PRs, comments, etc.)? This may happen because of that.

**Comment by tom-sherman** [comment]
I have 24 open PRs with around a total 100 comments, doesn't seem like a huge amount.

**Comment by tom-sherman** [comment]
It does look like I'm hitting a timeout, every request in the GQL Explorer is returning a 500 error after 10s with a tiny amount of variance.

**Comment by thomaslombart** [comment]
That's annoying. Are you able to avoid a timeout by tweaking some of the limits in the query?

**Comment by tom-sherman** [comment]
I tried removing some parts of the query and yes, if I start removing a chunk the request succeeds. I couldn't narrow it down to a single field that was bugged, it feels like hitting a query complexity limit.

**Comment by thomaslombart** [comment]
Thanks for looking into it. The query is a big one indeed, and you're not the only one who got this error. Maybe a way to solve this would be to run a query for each section (Open, Assigned, etc.) and run them in parallel to still get the result faster.

**Comment by thomaslombart** [comment]
Fixed in https://github.com/raycast/extensions/pull/11443.
