### ISSUE TITLE
[Spotify Player] fails to play songs.

### ISSUE THREAD

**Issue by shuvro111** [raycast/extensions#10454]
### Extension

https://raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Player command failed: Premium required
    at $n (/Users/shuvro/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/yourLibrary.js:61:118)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n (/Users/shuvro/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/yourLibrary.js:61:493)
```

### Steps To Reproduce

The Toggle Play/Pause option shows an error 

> "Unknown Error".

 However if I try to play from an playlist it gives the following error:

> "Player command failed: Premium required"

**Comment by shuvro111** [comment]
No, I'm not a premium user.

**Comment by peduarte** [comment]
I see, that's why it doesn't work. Some of the commands rely on APIs that are for premium only, as the error message says. Thanks!
