### ISSUE TITLE
[Spotify Player]  Failed to fetch (latest) data in library and searching song

### ISSUE THREAD

**Issue by SeongIkKim** [raycast/extensions#10489]
### Extension

https://raycast.com/mattisssa/spotify-player

#### Error: Failed to fetch data in my library
```
Error: Server error.
    at Vn (/Users/ike/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/yourLibrary.js:45:18421)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 5)
```
<img width="735" alt="image" src="https://github.com/raycast/extensions/assets/26772420/18a19244-0501-4454-aca8-6c1792ee3922">

#### Error: Failed to fetch latest data in search song
```
Error: Server error.
    at O0 (/Users/ike/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/search.js:65:8430)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 5)
```
<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/26772420/5124266a-7654-4f16-8b67-fe8b02188d0d">

Thanks for your working on great extension.

### Steps To Reproduce

1. Macbook M2 Pro
2. OSX Version 13.6.1 (22G313)
3. Korea, Seoul.

Everytime I use the command, it always fails(100%).

**Comment by BuddyLReno** [comment]
I'm not seeing this error (maybe I need to be in a special debug mode) but the Your Library search is definitely missing the vast majority of my saved albums and songs.

**Comment by peduarte** [comment]
Is this still happening? Works fine for me. Just wondering if the Spotify API was down?

**Comment by BuddyLReno** [comment]
Yeah :/ I'm not seeing an error but I'm certainly getting the same result. Searching for this band, Project 86, returns no result despite having added all their albums to my library. I've tried a number of other artists I've had saved but I don't get any results for them.

Search
<img width="790" alt="image" src="https://github.com/raycast/extensions/assets/1429547/fc30f978-1beb-4855-807e-131899c74e74">

In Spotify
![image](https://github.com/raycast/extensions/assets/1429547/e02e6bba-9257-4337-bc7d-d9df71f0a7ab)
![image](https://github.com/raycast/extensions/assets/1429547/2fd341b3-1862-4958-bb7a-7399f7126335)
![image](https://github.com/raycast/extensions/assets/1429547/6a1713c6-b880-4674-b71d-5c516e604763)

I've got a few in my library so they should be coming up. The only things I am able to search is anything that appears within the initial window when you open the command up.
<img width="799" alt="image" src="https://github.com/raycast/extensions/assets/1429547/0e199dde-1e6d-485d-ac2b-9febad5622fb">

Any of the artists that appear here will be present in the search. I can search Gojia and get that result but if I search any of their albums, it won't find them.

**Comment by peduarte** [comment]
I see. So, let me explain a couple of things

By default, the "Your Library" command will display 
- "Liked songs" Playlist
- Latest 6 Playlists
- Latest 6 Albums
- Latest 6 Artists
- Latest 6 liked songs
- Latest 6 Podcasts & Shows
- Latest 6 Episodes

The search will only search what's currently rendered, so you'll be searching across the items above

You can then use the dropdown (top right) to change the view, and see up to 50 results of each category. In that case, Search will search across the 50 items

Some things to note
- We are working on paginating the search results, so you'll be able to load more than 50
- We currently dont support searching for things that are not rendered in "Your Library" — I can understand this can be annoying, we could prob figure out a way to do a better job here — PR's welcome!

**Comment by BuddyLReno** [comment]
Ah that explains things! ok, just a misunderstanding on my part. Thanks!
