### ISSUE TITLE
[GitHub]...

### ISSUE THREAD

**Issue by gideonite** [raycast/extensions#10620]
### Extension

https://raycast.com/raycast/github

#### Error:
```
Error: GraphQL Error (Code: 401): {"response":{"message":"Bad credentials","documentation_url":"https://docs.github.com/graphql","status":401,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  pushedAt\n  stargazerCount\n  isArchived\n  isFork\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:recursecenter org:ratschlab org:DataScienceForGood org:ai2cm org:leap-stc archived:false sort:updated-desc","numberOfItems":100}}}
    at /Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:49846
    at p (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:43252)
    at Object.next (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:42556)
    at u (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:226:42114)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

Running "My GitHub Pull Requests" results in the error message (screenshot below)

<img width="758" alt="image" src="https://github.com/raycast/extensions/assets/2163686/640d5231-51d3-4bb6-8739-cfec5cc890b5">

**Comment by thomaslombart** [comment]
Could you log out and log back in to see if it fixes the issue?

**Comment by thomaslombart** [comment]
Closing to keep a clean backlog as there were no answers. Feel free to reopen the issue if the bug still appears.
