### ISSUE TITLE
[Set Audio Device] Connecting AirPlay devices like a HomePod doesn't work

### ISSUE THREAD

**Issue by michelvanheest** [raycast/extensions#10667]
### Extension

https://raycast.com/benvp/audio-device

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set devices to {}

    tell application "System Preferences"
      reveal pane id "com.apple.preference.sound"
    end tell
    tell application "System Events"
      tell application process "System Preferences"
        repeat until exists tab group 1 of window "Sound"
        end repeat
        tell tab group 1 of window "Sound"
          click radio button "Output"
          tell table 1 of scroll area 1
            set selected_row to (first UI element whose selected is true)
            set currentOutput to value of text field 1 of selected_row as text
            
            repeat with r in rows
              try
                set deviceName to value of text field 1 of r as text
                set deviceType to value of text field 2 of r as text
                set end of devices to { deviceName, deviceType }
              end try
            end repeat
          end tell
        end tell
      end tell
    end tell

    if application "System Preferences" is running then
      tell application "System Preferences" to quit
    end if
    
    return [ devices, "currentOutput", currentOutput ]
   
64:116: execution error: System Settings got an error: Can’t get pane id "com.apple.preference.sound". (-1728)
    at _t (/Users/michelvanheest/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:57)
    at /Users/michelvanheest/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ca (/Users/michelvanheest/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6806)
    at async b0 (/Users/michelvanheest/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6981)
```

<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/14166701/ddb7ad83-9295-486e-b162-6f02e738fc8f">

### Steps To Reproduce

1. macOS 13.6 (22G120), MacBook Air M2
2. ..?
3. Turn Airplay speakers on in settings
4. Try to run extension
<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/14166701/f1288f90-88a7-4597-b7d6-da9caaaa44d1">

### Current Behaviour

See error, can't use extension

### Expected Behaviour

Being able to connect HomePod

**Comment by michelvanheest** [comment]
Jowww @benvp can you check this out? Thanks!
