### ISSUE TITLE
[Spotify Player] Keeps getting logged out of the account

### ISSUE THREAD

**Issue by proffapt** [raycast/extensions#10824]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-02-19T13:38:30.457Z","data":{"function":"getApplications"}}]}: 


```

### Steps To Reproduce

1. Log in, it works
2. Use after sometime (no shutdown, but lock yes - if this might help)

**Comment by moisesrodriguez** [comment]
I'm having the same issue. I'm having to login probably about once per week and it's starting to get a little too much.

**Comment by proffapt** [comment]
Works fine now.
