### ISSUE TITLE
[Query ChatGPT] does not work

### ISSUE THREAD

**Issue by Gnosnay** [raycast/extensions#10883]
### Extension

https://raycast.com/cyxn/query-chatgpt

#### Error:
```
Error: Command failed with exit code 1: osascript
410:1524: execution error: Microsoft Edge got an error: Executing JavaScript through AppleScript is turned off. To turn it on, from the menu bar, go to View > Developer > Allow JavaScript from Apple Events. For more information: https://permanently-removed.invalid (12)
    at z4 (/Users/yansong/.config/raycast/extensions/d2c68917-097f-4a95-b72c-2ccd579bdab6/query-chatgpt-execute-custom-command.js:32:3043)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Na (/Users/yansong/.config/raycast/extensions/d2c68917-097f-4a95-b72c-2ccd579bdab6/query-chatgpt-execute-custom-command.js:89:137)
    at async Object.Ta (/Users/yansong/.config/raycast/extensions/d2c68917-097f-4a95-b72c-2ccd579bdab6/query-chatgpt-execute-custom-command.js:89:408)
```

### Steps To Reproduce

my linke is 
`raycast://extensions/cyxn/query-chatgpt/query-chatgpt-execute-custom-command?arguments=%7B%22prompt%22%3A%22Please%20help%20me%20find%20solution%20or%20result%20for%20following%20questions%3A%5Cn%22%2C%22gptUrl%22%3A%22https%3A%2F%2Fchat.openai.com%2F%3Fmodel%3Dgpt-4%22%2C%22query%22%3A%22{Query}%22%7D`

**Comment by Gnosnay** [comment]
after o
