### ISSUE TITLE
[Arc] access spaces and favorites `Can’t get window 1. Invalid index.`

### ISSUE THREAD

**Issue by vovsemenv** [raycast/extensions#10888]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
Error: Command failed with exit code 1: osascript
98:549: execution error: Arc got an error: Can’t get window 1. Invalid index. (-1719)
    at gf (/Users/vladimirsemenov/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/menu-bar.js:32:3080)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async vi (/Users/vladimirsemenov/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/menu-bar.js:152:32)
```

### Steps To Reproduce

Just click access spaces and favorites

**Comment by leotuil-ast** [comment]
Is your arc window minimize, or is your Arc app not open? @vovsemenv

**Comment by vovsemenv** [comment]
maximize helps

**Comment by leotuil-ast** [comment]
@vovsemenv we could still handle that on our side so you won't need to have it maximized I will take a look.

**Comment by vovsemenv** [comment]
So i also installed Arc after installing the extention. maybe thats the case 🙏
