### ISSUE TITLE
[Jira] Error thrown when using all commands

### ISSUE THREAD

**Issue by cank** [raycast/extensions#10894]
### Extension

https://raycast.com/raycast/jira

#### Error:
```
Error: {"errorMessages":["Could not find an avatar matching the provided parameters."],"errors":{}}
    at eo (/Users/***/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/watched-issues.js:95:2143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/***/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/watched-issues.js:95:3670
    at async Promise.all (index 0)
    at async IL (/Users/***/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/watched-issues.js:95:3602)
```

### Steps To Reproduce

1. Authenticate Jira successfully
2. Run `Open Issues`

### Current Behaviour

Error is returned form Jira:

`Error: {"errorMessages":["Could not find an avatar matching the provided parameters."],"errors":{}}`

### Expected Behaviour

Jira commands work

**Comment by cank** [comment]
Couldn't find any broken icons in jira, but I deauthorized the raycast app in the Jira interface and now it's working.
