### ISSUE TITLE
 [Google Chrome]  The "New Tab" command crashes upon the first start or when a new profile is added.

### ISSUE THREAD

**Issue by nagauta** [raycast/extensions#10921]
### Extension

https://www.raycast.com/Codely/google-chrome

#### overview
The "New Tab" command crashes upon the first start or when a new profile is added.

#### hypothesis
I suspect this bug is related to the implementation found [here](https://github.com/raycast/extensions/blob/98c8b369fee24124635131f302a9b7fc7f6dda13/extensions/google-chrome/src/new-tab.tsx#L27), potentially violating [React's rules of hooks](https://ja.legacy.reactjs.org/docs/hooks-rules.html) under specific conditions:

##### case1
Initially, the profile count is 0. After loading, the count increases, as seen [here](https://github.com/raycast/extensions/blob/98c8b369fee24124635131f302a9b7fc7f6dda13/extensions/google-chrome/src/components/ChromeProfileDropdown.tsx#L13).
UseSQL, which incorporates hooks, is then executed repeatedly.

##### case2
Upon adding a new profile, the initial rendering shows more than one profile. The profile count continues to increase after loading, as mentioned above.
Again, UseSQL is executed in a loop, causing potential issues.

#### about error output
there's error outputted in terminal below.

```
Warning: React has detected a change in the order of Hooks called by Command. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useRef                     useRef
3. useRef                     useRef
4. useSyncExternalStore       useSyncExternalStore
5. useMemo                    useMemo
6. useRef                     useRef
7. useCallback                useCallback
8. useRef                     useRef
9. useRef                     useRef
10. useSyncExternalStore      useSyncExternalStore
11. useMemo                   useMemo
12. useRef                    useRef
13. useCallback               useCallback
14. useState                  useState
15. useState                  useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Command (/Users/myano/.config/raycast/extensions/google-chrome/new-tab.js:7366:66)
    at Dr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:2490)
    at ray-navigation-stack
    at Lo (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:2088)
    at Suspense
    at Or (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:10:1022)
    at ray-root
    at Bi (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:3000)
00:52:39.091 The above error occurred in the <Command> component:

    at Command (/Users/myano/.config/raycast/extensions/google-chrome/new-tab.js:7366:66)
    at Dr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:2490)
    at ray-navigation-stack
    at Lo (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:2088)
    at Suspense
    at Or (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:10:1022)
    at ray-root
    at Bi (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:11:3000)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalErrorBoundary.
00:52:39.123 
TypeError: Cannot create property 'current' on boolean 'true'

Command:new-tab.tsx:24:55

---
21: }
22: 
23: export default function Command() {
24:   const [searchText, setSearchText] = useState<string>();
25:   const [profiles] = useCachedState<ChromeProfile[]>(CHROME_PROFILES_KEY);
26:   const [profile] = useCachedState(CHROME_PROFILE_KEY, DEFAULT_CHROME_PROFILE_ID);
27:   const profileHistories = profiles?.map((p) => ({ ...useHistorySearch(p.id, searchText), profile: p }));
---

Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088
```

### Steps To Reproduce

Pattern A: 
1. Install [Google Chrome Extension](https://www.raycast.com/Codely/google-chrome)
2. Excute "New Tab" command
![スクリーンショット 2024-02-24 0 52 43](https://github.com/raycast/extensions/assets/44369261/4ee12bc1-9b94-419b-b041-14736315394b)

Pattern B: 
1. add a new profile on Google Chrome
2. Excute "New Tab" command

### Current Behaviour

![スクリーンショット 2024-02-24 0 52 43](https://github.com/raycast/extensions/assets/44369261/eac3eb98-3f9b-42d3-ac76-f2652ddc74ce)

### Expected Behaviour

<img width="743" alt="スクリーンショット 2024-02-24 1 01 09" src="https://github.com/raycast/extensions/assets/44369261/206900d6-3b8a-48f2-b565-391c4062933a">

**Comment by nagauta** [comment]
This will happen with other browser extensions like MS Edge, as they use Chromium.
