### ISSUE TITLE
[Set Audio Device] does not fetch device list when "include Airplay devices" is enabled

### ISSUE THREAD

**Issue by ghost** [raycast/extensions#10934]
### Extension

https://raycast.com/benvp/audio-device

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set devices to {}

    tell application "System Preferences"
      reveal pane id "com.apple.preference.sound"
    end tell
    tell application "System Events"
      tell application process "System Preferences"
        repeat until exists tab group 1 of window "Sound"
        end repeat
        tell tab group 1 of window "Sound"
          click radio button "Output"
          tell table 1 of scroll area 1
            set selected_row to (first UI element whose selected is true)
            set currentOutput to value of text field 1 of selected_row as text
            
            repeat with r in rows
              try
                set deviceName to value of text field 1 of r as text
                set deviceType to value of text field 2 of r as text
                set end of devices to { deviceName, deviceType }
              end try
            end repeat
          end tell
        end tell
      end tell
    end tell

    if application "System Preferences" is running then
      tell application "System Preferences" to quit
    end if
    
    return [ devices, "currentOutput", currentOutput ]
   
64:116: execution error: System Settings got an error: Can’t get pane id "com.apple.preference.sound". (-1728)
    at _t (/Users/pottersfield/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:57)
    at /Users/pottersfield/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ca (/Users/pottersfield/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6806)
    at async b0 (/Users/pottersfield/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6981)
```

### Steps To Reproduce

Enable "Include AirPlay devices" in settings and you get the error message.
Disable "Include AirPlay devices" in settings and it works, but only shows generic "AirPlay" when current connected device is an AirPlay device, but no name. 

https://github.com/alanhg/switchaudio-osx commit on switchaudio-osx seems to fix the AirPlay issues.

**Comment by pointbreakd** [comment]
Still an issue.

**Comment by theomax13** [comment]
Same here still not fixed

**Comment by pottersfield** [comment]
I personally switched to Keyboard Maestro macro which I can configure to switch to specific AirPlay devices. This works for weeks/months now flawlessly.

https://forum.keyboardmaestro.com/t/macro-set-sound-output-v7-1/23959

**Comment by Ptujec** [comment]
@benvp If you are interested, I have a working [AppleScript for the AirPlay part](https://github.com/Ptujec/LaunchBar/blob/d37f139e87b1d1be59294797655916d8ffb1b55d/Audio-Devices/Audio%20Devices.lbaction/Contents/Scripts/default.swift#L323) in my LaunchBar action.

**Comment by abraver** [comment]
+1

**Comment by LuckyTheCoder** [comment]
+1

**Comment by bnch-gbegur** [comment]
still an issue
