### ISSUE TITLE
[Set Audio Device]...

### ISSUE THREAD

**Issue by Guolin-Yin** [raycast/extensions#11131]
### Extension

https://raycast.com/benvp/audio-device

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set devices to {}

    tell application "System Preferences"
      reveal pane id "com.apple.preference.sound"
    end tell
    tell application "System Events"
      tell application process "System Preferences"
        repeat until exists tab group 1 of window "Sound"
        end repeat
        tell tab group 1 of window "Sound"
          click radio button "Output"
          tell table 1 of scroll area 1
            set selected_row to (first UI element whose selected is true)
            set currentOutput to value of text field 1 of selected_row as text
            
            repeat with r in rows
              try
                set deviceName to value of text field 1 of r as text
                set deviceType to value of text field 2 of r as text
                set end of devices to { deviceName, deviceType }
              end try
            end repeat
          end tell
        end tell
      end tell
    end tell

    if application "System Preferences" is running then
      tell application "System Preferences" to quit
    end if
    
    return [ devices, "currentOutput", currentOutput ]
   
64:116: execution error: System Settings got an error: Can’t get pane id "com.apple.preference.sound". (-1728)
    at _t (/Users/colinguolin/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:57)
    at /Users/colinguolin/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ca (/Users/colinguolin/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6806)
    at async b0 (/Users/colinguolin/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6981)
```

### Steps To Reproduce

error in "Set Output Device"

### Current Behaviour

can fetch the output device in raycast

### Expected Behaviour

get the existing output device

**Comment by iamyeizi** [comment]
I add to the report that this error only happens if you have activated the Airplay option.

![CleanShot 2024-03-10 at 8  13 07](https://github.com/raycast/extensions/assets/37552350/63a97064-4087-4620-9613-053da270ce77)

**Comment by antonengelhardt** [comment]
@iamyeizi 

I tried it with Automators "Watch me do" (look [here](https://apple.stackexchange.com/a/315091/510849)), and then with XCode's Accessibility Inspector (look [here](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/AutomatetheUserInterface.html#//apple_ref/doc/uid/TP40016239-CH69-SW1:~:text=Accessibility%20Inspector%20(Figure%2037%2D3)%20makes%20it%20even%20easier%20to%20identify%20user%20interface%20element%20information.%20This%20app%20is%20included%20with%20Xcode.%20To%20use%20it%2C%20open%20Xcode%20and%20select%20Xcode%20%3E%20Open%20Developer%20Tool%20%3E%20Accessibility%20Inspector.)) and a lot of ChatGPT/Perplexity.

I am currently stuck with this:

```
  set devicesList to {} -- Stores output device names
  set currentOutput to "" -- Name of currently used output device

  tell application "System Events"
      tell application "System Settings"
          reveal pane id "com.apple.Sound-Settings.extension" -- Correctly opens the Sound settings pane
          delay 0.5 -- Wait for the pane to display fully, increased delay for slower UI response
      end tell

      tell process "System Settings"
          -- Wait for and click the Output tab using the path obtained from Watch Me Do
          click group 1 of UI element 1 of row 2 of outline 1 of scroll area 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
          delay 2 -- Allow time for the output devices list to become visible and interactive

          -- Interact with the outline containing devices
          tell outline 1 of scroll area 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
              set numDevices to count rows
              repeat with i from 3 to numDevices - 1
                  set thisDevice to row i
                  set deviceName to value of static text 1 of group 1 of UI element 1 of thisDevice
                  set end of devicesList to deviceName -- Append device name to list
                  -- Identify the currently selected device
                  if selected of thisDevice then
                      set currentOutput to deviceName
                  end if
              end repeat
          end tell
      end tell

      -- Close System Settings after operations are complete
      if application "System Settings" is running then
          tell application "System Settings" to quit
      end if
  end tell

  return {devicesList, "currentOutput", currentOutput}
```
This snippet is not "done" and ready to be used, just my progress so far.

Nevertheless, the execution of this Apple Script is **INCREDIBLY** slow (sometimes i takes 4 minutes in the Apple Script editor with 8 devices). I am not sure if there is any other way to manipulate and get the devices... just leaving my thought for now...

And also i think this issue should be reopened, as it contains the most information about the problem (@thomaslombart), #10667 #10934 #12672 are duplicates in that sense...

**Comment by antonengelhardt** [comment]
[This](https://apple.stackexchange.com/questions/213011/any-way-to-change-sound-output-device-via-applescript-or-shell) could be interesting. The only downside is the need for a dependency

**Comment by iamyeizi** [comment]
I have no problem with this extension, it works fine for me

**Comment by antonengelhardt** [comment]
> @antonengelhardt I have no problem with this extension, it works fine for me

Also with the AirPlay Setting turned on?

**Comment by iamyeizi** [comment]
> > @antonengelhardt I have no problem with this extension, it works fine for me
> 
> Also with the AirPlay Setting turned on?

I just tried that, I don't have AirPlay speaker, if you use AirPlay it doesn't work as you mention

**Comment by antonengelhardt** [comment]
> > > @antonengelhardt I have no problem with this extension, it works fine for me
> 
> > 
> 
> > Also with the AirPlay Setting turned on?
> 
> 
> 
> I just tried that, I don't have AirPlay speaker, if you use AirPlay it doesn't work as you mention

Yes, exactly. Actually you brought that up a few months ago. I just had the same problem and found this issue. I'm still trying to fix it...

**Comment by iamyeizi** [comment]
@antonengelhardt I was able to get an AirPlay enabled device to test.

I also found 2 ways to get this to work, one using swift and one using a command that comes in the system. Now I'm going to try to put the swift and applescript outputs together.

Try if you can do something with the output of `dns-sd` (_Multicast DNS (mDNS) & DNS Service Discovery (DNS-SD) Test Tool_), remember to get the local name of where the extension runs to exclude it from the final list (**iCloud name device**, isn't the same as the Sharing name, aka "Local hostname"), since your macbook is capable of receiving, it will appear.

**Command:** `dns-sd -B _raop._tcp`

**Comment by JoeRoddy** [comment]
Issue currently happening for me.  With airplay toggled on, trying to connect to my Homepod.

![image](https://github.com/raycast/extensions/assets/16690442/d0510f94-e173-4b31-85da-8cd0470734eb)

If I disable Airplay, I'm able to see my MBP speakers, but that's not particularly helpful.

**Comment by iamyeizi** [comment]
@JoeRoddy Hey! Yeah, it's because airplay devices are now not accessible from applescript, you need to trigger this with an API. I'm trying to figure it out

**Comment by antonengelhardt** [comment]
Keep it open

**Comment by pasteley** [comment]
Patched [getOutputDevices](https://github.com/raycast/extensions/blob/dfc1ec2398d62375066cc4ec16ede7476b2f4218/extensions/audio-device/src/utils.tsx#L13) from me:

```applescript
set devices to {}

tell application "System Settings"
	activate -- REQUIRED FOT AIRPLAY DEVICES
	reveal pane id "com.apple.Sound-Settings.extension"
end tell

tell application "System Events" to tell application process "System Settings"
	repeat until exists window "Sound"
	end repeat
	tell group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
		click radio button 1 of tab group 1
		
		tell outline 1 of scroll area 1
			set selected_row to (first UI element whose selected is true)
			set currentOutput to value of static text of group 1 of UI element 1 of selected_row as text
			
			repeat with r in rows
				try
					set deviceName to value of static text of group 1 of UI element 1 of r as text
					set deviceType to value of static text of group 1 of UI element 2 of r as text
					set end of devices to {deviceName, deviceType}
				end try
			end repeat
		end tell
	end tell
end tell

tell application "System Settings" to quit
return [devices, "currentOutput", currentOutput]
```
This works without even without delay for me but System Settings app pop ups this way.
There is another way to implement it using `ControlCenter`:
```
set deviceNames to {}

tell application "System Events"
	tell its application process "ControlCenter"
		set soundMenu to menu bar item 5 of menu bar 1
		click soundMenu
		delay 0.5
		tell window 1
			tell its group 1				
				set deviceElements to checkboxes of scroll area 1
				repeat with deviceElement in deviceElements
					set deviceMenuName to value of attribute "AXIdentifier" of deviceElement
					set deviceName to text 14 thru -1 of deviceMenuName -- trim 'sound-device-' prefix
					if value of attribute "AXValue" of deviceElement as boolean is true then
						set currentOutput to deviceName
					end if
					set end of deviceNames to deviceName
				end repeat
			end tell
		end tell
		click soundMenu
	end tell
end tell

return [deviceNames, "currentOutput", currentOutput] -- WITHOUT TYPE OF DEVICE (BUILT-IN, BT, AIRPLAY)
```
But all of those solutions looks horrible, it would be much better to support it directly via coreaudio lib here: 
- https://github.com/karaggeorge/macos-audio-devices/issues/22
- https://gist.github.com/kdepp/46c812b05cda6e44a292328b31d0784c

**Comment by iamyeizi** [comment]
> ```applescript
> devices
> ```

Hi! 👋🏽 None of these solutions work for me at my local, how did u implement it?

**Comment by iamyeizi** [comment]
Hi! @pasteley 👋🏽 None of these solutions work for me at my local, how did u implement it?

**Comment by Bonapara** [comment]
> Hi! @pasteley 👋🏽 None of these solutions work for me at my local, how did u implement it?

Same, doesn't work here

**Comment by Bonapara** [comment]
keep it open

**Comment by LuckyTheCoder** [comment]
+1
