### ISSUE TITLE
[Spotify Player] ... I need to sign in into my account many times trough the day

### ISSUE THREAD

**Issue by feldman22** [raycast/extensions#12060]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Ar (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6250)\n    at pt (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6375)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6140)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-04-28T15:43:56.256Z","data":{"function":"getApplications"}}]}: OAuth request creation is not available when command is launched in background


```

### Steps To Reproduce

1. In production
2. After login and using the extension for a while
3. I see an error and then I get asked to log in again
4. When seeing the details of my Spotify account I see that the RayCast extension is active but I can't use the extension due to that error
5. I finally have to log in again in order to use it, which is annoying since it's happening after a couple of hours

**Comment by lucasmpramos** [comment]
no news here?

**Comment by erics118** [comment]
See #9988

**Comment by erics118** [comment]
@raycastbot close this issue
