### ISSUE TITLE
[Spotify Player] Did not play upon request

### ISSUE THREAD

**Issue by medio4** [raycast/extensions#12107]
### Extension

https://raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Player command failed: Restriction violated
    at Rn (/Users/jacob/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/nowPlaying.js:63:1939)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n (/Users/jacob/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/nowPlaying.js:65:299)
```

### Steps To Reproduce

1. In the now-playing menu
2. Hit play

**Comment by medio4** [comment]
I have spotify premium

**Comment by thomaslombart** [comment]
Are you getting this error consistently for all commands?
