### ISSUE TITLE
[Battery Optimizer] Asks to install bclm when it has been already installed

### ISSUE THREAD

**Issue by danulqua** [raycast/extensions#12756]
### Extension

https://www.raycast.com/Qetesh/battery-optimizer

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

I installed `bclm` and even tried to restart Raycast, but extension always asks me to install `bclm`.

![CleanShot 2024-06-04 at 10 57 53@2x](https://github.com/raycast/extensions/assets/38916225/a5109741-2e4b-4a80-b164-1dc8dc847141)

### Steps To Reproduce

1. Install extension
2. Install `bclm`
3. Restart Raycast
4. Open any command

### Current Behaviour

Commands not working - extension asks to install `bclm`

### Expected Behaviour

Extension finds `bclm` and opens commands without any issues

**Comment by Qetesh** [comment]
Thank you for using the extension and for your feedback. The extension uses the `which` system command to verify the `bclm` path. Could you please provide the output of the following command:

```Bash
zsh -l -c 'which bclm'
```
This will help me identify the cause of the issue. Thank you!

**Comment by danulqua** [comment]
@Qetesh The output of this command is

```
/opt/homebrew/bin/bclm
```

**Comment by Qetesh** [comment]
This is the expected result. I tested in a fresh environment, installing only Raycast, Brew, BCLM, and this store extension, and did not encounter any issues. I am still debugging. If possible, please provide any additional executable information. Thank you!

> @Qetesh The output of this command is
> 
> ```
> /opt/homebrew/bin/bclm
> ```

**Comment by danulqua** [comment]
I ended up forking the extension in order to try to debug the `commandExists` function.
`execSync` throws an error only when trying to use `bclm`, even with `which` command:

```
10:07:09.698 Error: Command failed: zsh -l -c 'which bclm'
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at commandExists (/Users/danulqua/.config/raycast/extensions/battery-optimizer/get_battery_threshold.js:37:52)
    at confirmAlertBrew (/Users/danulqua/.config/raycast/extensions/battery-optimizer/get_battery_threshold.js:44:8)
    at getChargeThreshold (/Users/danulqua/.config/raycast/extensions/battery-optimizer/get_battery_threshold.js:73:29)
    at Object.get_battery_threshold_default (/Users/danulqua/.config/raycast/extensions/battery-optimizer/get_battery_threshold.js:87:9)
    at QR (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:36572)
    at KR (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:36192)
    at MessagePort.<anonymous> (<…>
```

Also I tried to specify the exact `zsh` path, both the `/bin/zsh` and `/opt/homebrew/bin/zsh` work the same.

Hopefully, it helps.

**Comment by Qetesh** [comment]
@minikdev I'm also on Apple silicon. What macOS version is it? I'm gonna install it for a test.

**Comment by minikdev** [comment]
Hi @Qetesh, I'm using macOS Sonoma 14.5, the latest version apparently. Thanks.

**Comment by danulqua** [comment]
`MacBook Pro M2 Max`
`macOS Sonoma 14.5` as well

**Comment by Qetesh** [comment]
Thanks for the feedback. I’m on macOS Sonoma 14.5, and it’s working fine. So weird.
During testing, I found that running Raycast with Rosetta 2 on Apple Silicon causes some strange errors. Hope this helps.

**Comment by Qetesh** [comment]
Hey guys,

Thanks to VatsalSy for adding PR #13000. If the auto-detect BCLM feature doesn’t work, you can now use the specified path option. We’ve also optimized the execution logic and logging.
