### ISSUE TITLE
[Bitwarden Vault] Search Vault error: diskAccount.profile is null

### ISSUE THREAD

**Issue by harababurel** [raycast/extensions#13663]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.79.1

### macOS Version

Apple M3 Pro, macOS Sonoma 14.5

### Description

**Search Vault** command instantly errors after entering my bitwarden master password.

![screenshot](https://i.imgur.com/6GBKZuC.png)

#### Error:
```
Error: Command failed with exit code 1: /opt/homebrew/bin/bw status
/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36503
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^

TypeError: Cannot read properties of null (reading 'profile')
    at StateService.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36503:62)
    at Generator.next (<anonymous>)
    at /opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36411:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36407:12)
    at /opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36498:61
    at StateService.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:37119:44)
    at Generator.next (<anonymous>)
    at /opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36411:71
    at new Promise (<anonymous>)

Node.js v20.9.0

/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36503
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^
```

### Steps To Reproduce

1. Install **Bitwarden Vault** extension from store
2. Configure it with **Client ID**, **Client Secret** (as copied from the `Settings > Security > API Keys` page on the Bitwarden web UI), **Bitwarden CLI Path** (`/opt/homebrew/bin/bw`, which exists on my machine)
3. Run **Search Vault** command
4. It shows a form with 2 fields: `Vault Status: ...` and `Master password: [text input]`
5. Sometimes it lets me enter the password and then errors. Other times it errors instantly after less then half a second (with no input from me).

I cleaned the extension local data and reinstalled the extension, no luck. 

The `bw` CLI works as expected:

```shellsession
$ which bw
/opt/homebrew/bin/bw
```

```shellsession
$ bw unlock
(node:29399) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
mac failed.
? Master password: [hidden]
Your vault is now unlocked!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="########################################################################################"
> $env:BW_SESSION="########################################################################################"

You can also pass the session key to any command with the `--session` option. ex:
$ bw list items --session ########################################################################################
```

```shellsession
$ bw status
(node:29435) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
mac failed.
{"serverUrl":null,"lastSync":"2024-07-25T09:06:12.300Z","userEmail":"###########################","userId":"####################################","status":"locked"}
```

```shellsession
$ bw list items --search github
(node:31079) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
mac failed.
? Master password: [hidden]
[{"passwordHistory":null,"2021-03-01T15:11:55.927Z", ... }]
```

### Current Behaviour

**Search Vault** command errors out, see "Description" for details.

### Expected Behaviour

**Search Vault** should work as expected after entering the correct master password.

**Comment by jomifepe** [comment]
Hello, the CLI has demonstrated to be very inconsistent and a lot of new bugs have been appearing. Since you're using the latest and I've heard about other issues with it, I suggest trying to use `2024.6.0`. https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439

**Comment by harababurel** [comment]
Thanks for confirming, then I suppose this can be closed as a duplicate of https://github.com/raycast/extensions/issues/13329 since it doesn't look actionable.

**Comment by jomifepe** [comment]
Yeah, I was waiting for a response from the person who created the issue
