### ISSUE TITLE
[ChatGPT] Unexpected Toast Error Displayed: Failed to fetch latest data

### ISSUE THREAD

**Issue by husniadil** [raycast/extensions#13861]
### Extension

https://raycast.com/abielzulio/chatgpt

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

When creating or editing `Models`, a Toast error appears, **even though the functionality still operates correctly**. I am still able to create and edit models.

#### Error:
```
Error: Invalid Closing Quote: got "T" at line 170 instead of delimiter, record delimiter, trimable character (if activated) or comment
    at Object.parse (/Users/husni/.config/raycast/extensions/35fa3856-f360-465f-885c-acf4ebcf19b1/model.js:108:2103)
    at US (/Users/husni/.config/raycast/extensions/35fa3856-f360-465f-885c-acf4ebcf19b1/model.js:110:1218)
    at Object.parseResponse [as current] (/Users/husni/.config/raycast/extensions/35fa3856-f360-465f-885c-acf4ebcf19b1/model.js:110:2678)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/husni/.config/raycast/extensions/35fa3856-f360-465f-885c-acf4ebcf19b1/model.js:63:7511
```
<img width="765" alt="image" src="https://github.com/user-attachments/assets/49f92fce-51a9-42e4-8036-8bdeeecd6332">
[](url)

### Steps To Reproduce

1. Open Models
2. From the Action Panel, either select Create Model or Edit Model.
3. A new screen to create/edit model is displayed with Toast error.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/49f92fce-51a9-42e4-8036-8bdeeecd6332">

### Current Behaviour

It shows a Toast error:

<img width="765" alt="image" src="https://github.com/user-attachments/assets/49f92fce-51a9-42e4-8036-8bdeeecd6332">

### Expected Behaviour

It should not display any errors.

**Comment by husniadil** [comment]
I raised a PR https://github.com/raycast/extensions/pull/13951

**Comment by husniadil** [comment]
@raycastbot assign me
