### ISSUE TITLE
[Ollama AI] Does not connect to localhost:11434

### ISSUE THREAD

**Issue by tgunr** [raycast/extensions#13919]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

Ollama is installed and running. I can use ollama list and ollama run llama3.1:latest model in terminal just fine. After installing the Raycast extension, I tried using manage models and get "Local Server" the operation was aborted. 
![image](https://github.com/user-attachments/assets/442e33c7-9b47-46da-97cd-ed25e2881819)

If I try to use "Pull Model" with llama3.1:latest I get
![image](https://github.com/user-attachments/assets/c4b013e6-6280-4723-bb44-344521073d60)

The model llama3.1:latest is already installed. 

What am I doing wrong?

### Steps To Reproduce

Install ollama
Install extension
Try to use oolama

### Current Behaviour

Cannot connect 

### Expected Behaviour

Expected I could connect to localhost:11434

**Comment by tgunr** [comment]
Tried to build the extension and when selecting "Manage Models" I got this:

` % npm run dev                                                 (main)extensions

> dev
> ray develop

info  -  entry points [src/ollama-chat.tsx src/ollama-browser-summarize.tsx src/ollama-casual.tsx src/ollama-code-explain.tsx src/ollama-confident.tsx src/ollama-explain.tsx src/ollama-fix-spelling-grammar.tsx src/ollama-friendly.tsx src/ollama-image-describe.tsx src/ollama-image-to-text.tsx src/ollama-improve-writing.tsx src/ollama-longer.tsx src/ollama-professional.tsx src/ollama-shorter.tsx src/ollama-translate.tsx src/ollama-tweet.tsx src/ollama-models.tsx src/ollama-custom-create.tsx src/ollama-custom-command.tsx]
info  -  compiled entry points
info  -  generated extension's TypeScript definitions
ready -  built extension successfully
03:04:54.895 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Command`. See https://reactjs.org/link/warning-keys for more information.
    at hu (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:21000)
    at Command (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:14649:10)
    at _r (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2593)
    at ray-navigation-stack
    at Eo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2094)
    at Suspense
    at Nr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:7:2335)
    at ray-root
    at Oi (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:3103)
03:04:55.038 Error: The operation was aborted.
03:04:55.038 Stack trace: AbortError: The operation was aborted.
    at abort (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13244:21)
    at EventTarget.abortAndFinalize (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13259:7)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at EventTarget.dispatchEvent (node:internal/event_target:755:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at Timeout._onTimeout (node:internal/abort_controller:127:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
03:04:55.039 Error: The operation was aborted.
03:04:55.040 Stack trace: AbortError: The operation was aborted.
    at abort (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13244:21)
    at EventTarget.abortAndFinalize (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13259:7)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at EventTarget.dispatchEvent (node:internal/event_target:755:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at Timeout._onTimeout (node:internal/abort_controller:127:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
03:04:55.042 Error: The operation was aborted.
03:04:55.042 Stack trace: AbortError: The operation was aborted.
    at abort (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13244:21)
    at EventTarget.abortAndFinalize (/Users/davec/.config/raycast/extensions/raycast-ollama/ollama-models.js:13259:7)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at EventTarget.dispatchEvent (node:internal/event_target:755:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at Timeout._onTimeout (node:internal/abort_controller:127:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)`

**Comment by husniadil** [comment]
I was unable to replicate this issue, please refer to my screencast below:

![ollama](https://github.com/user-attachments/assets/474fed2e-bcce-4a24-8528-b077741ef359)
