### ISSUE TITLE
[Slack]  A rate-limit has been reached

### ISSUE THREAD

**Issue by obaidch24** [raycast/extensions#14113]
### Extension

https://raycast.com/mommertf/slack

### Raycast Version

1.81.2

### macOS Version

14.6.1

#### Error:
```
Error: A rate-limit has been reached, you may retry this request in 30 seconds
    at n5 (/Users/obaid.samadian/.config/raycast/extensions/d5d27df2-9818-41ea-b683-0e4af3f4be3d/search.js:43:25526)
    at e.<anonymous> (/Users/obaid.samadian/.config/raycast/extensions/d5d27df2-9818-41ea-b683-0e4af3f4be3d/search.js:45:10270)
    at Generator.next (<anonymous>)
    at p (/Users/obaid.samadian/.config/raycast/extensions/d5d27df2-9818-41ea-b683-0e4af3f4be3d/search.js:45:2332)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. Open Channel

**Comment by thomaslombart** [comment]
Are you getting this consistently, or does the error go away after a few seconds or minutes? If the latter happens, it's normal behavior.

**Comment by obaidch24** [comment]
Always happens.

**Comment by obaidch24** [comment]
> Are you getting this consistently, or does the error go away after a few seconds or minutes? If the latter happens, it's normal behavior.

Always

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by obaidch24** [comment]
> Could you share a recording? It'll make it easier to see what's happening.

Sure.

https://github.com/user-attachments/assets/ac70752c-7442-4ec8-86c2-309b117ce16e

**Comment by obaidch24** [comment]
@thomaslombart When I try to select `Unread messages` or `Open Channel` for the first time, it shows loading for more than 1 minute and then throws a rate-limit error. After that, it immediately throws the rate-limit error.

**Comment by Elliot67** [comment]
@obaidch24 Are you in a very large Slack workspace ? How many users and public channels are in it ?

---

Rate limiting might be the alternative ending to #13067 .
[`users.list`](https://api.slack.com/methods/users.list) and [`conversations.list`](https://api.slack.com/methods/conversations.list) are both rate limited "Tier 2" (20 requests per minute).

We can retrieve 1_000 users per requests and 1_000 conversations which means rate limiting could start to appear on workspace with more than ~15k users.

Simplest solution is to fetch and cache all the data bit by bit, preferably in the background if raycast allows it.

**Comment by obaidch24** [comment]
> @obaidch24 Are you in a very large Slack workspace ? How many users and public channels are in it ?
> 
> Rate limiting might be the alternative ending to #13067 . [`users.list`](https://api.slack.com/methods/users.list) and [`conversations.list`](https://api.slack.com/methods/conversations.list) are both rate limited "Tier 2" (20 requests per minute).
> 
> We can retrieve 1_000 users per requests and 1_000 conversations which means rate limiting could start to appear on workspace with more than ~15k users.
> 
> Simplest solution is to fetch and cache all the data bit by bit, preferably in the background if raycast allows it.

Yes, the workspace is quite large. I'm not sure how many users and public channels it has. I guess it should have more than 4K active users.

**Comment by thomaslombart** [comment]
It could indeed be due to the large workspace. @obaidch24, if you have other Slack workspaces, could you test the extension in a smaller one and let me know if it works?

**Comment by obaidch24** [comment]
> It could indeed be due to the large workspace. @obaidch24, if you have other Slack workspaces, could you test the extension in a smaller one and let me know if it works?

Unfortunately, I don't have another one.

**Comment by obaidsamadian** [comment]
@Elliot67 @thomaslombart Will this issue be addressed?

**Comment by thomaslombart** [comment]
I'm fully-focused on another project, so I won't have much bandwidth for that. Please feel free to submit a PR, and I'll review it 🙂

**Comment by thomaslombart** [comment]
Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)

**Comment by jhasubhash** [comment]
I tried implementing this locally. 
But it's look like rate limit is not the only issue. 
I soon ran into another issue with large userList / conversationList

`Error: Worker terminated due to reaching memory limit: JS heap out of memory`

This maybe because we are loading profile images as well. But I am not sure. 

Also, the first issue of rate limit remain unsolved event after updating following code
```JS
- slackWebClient = new WebClient(token, { rejectRateLimitedCalls: true });
+ slackWebClient = new WebClient(token, { retryConfig: retryPolicies.fiveRetriesInFiveMinutes });
```

Furthermore I am seeing multiple calls (four calls) to `getSlackMembers` and `getConversations` , which seems redundant. 

I believe it will take some time to figure out how to fix all these things.

**Comment by jhasubhash** [comment]
I have made the change and it should work in most of the cases. 
But I am unable to raise a PR for review.
While executing 
```JS
npx @raycast/api@latest publish
```
I am running into following

```
You reached the limit of commands of the free plan for your organization. Upgrade your plan here:
https://raycast.com/upgrade/subhashjha/gNoWf5Jm1xmpXrez
```
@thomaslombart  Do I need to upgrade my account or is there a workaround ?

**Comment by deinspanjer** [comment]
I'm just starting out with Raycast and got my org to approve this extension in Slack, but I'm hitting the exact same problems described here.

Are there any further developments to allow users in large Slack organizations to use the extension?
