### ISSUE TITLE
[Weather]...bug

### ISSUE THREAD

**Issue by csabyyka** [raycast/extensions#14325]
### Extension

https://raycast.com/tonka3000/weather

### Raycast Version

1.81.2

### macOS Version

14.6.1

#### Error:
```
Error: Server-side issue at wttr.in (503). Please try again later
    at ud.fetch (/Users/hajnalcsaba/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:36:10696)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ud.getWeather (/Users/hajnalcsaba/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:36:10789)
    at async Ri.keepPreviousData (/Users/hajnalcsaba/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:36:15646)
```

### Steps To Reproduce

Sorry i am not an expert, the extension just stoped working today
<img width="862" alt="SCR-20240904-bvig" src="https://github.com/user-attachments/assets/af8cc958-6112-4320-a68c-90577a53c68c">

**Comment by tonka3000** [comment]
@csabyyka Should work again. This happens when the backend wttr.in is down.

**Comment by csabyyka** [comment]
Ohh I see! Thanks the information!

**Comment by tonka3000** [comment]
@raycastbot close this issue
