### ISSUE TITLE
[Spotify Player] says "bad gateway" when play/pausing

### ISSUE THREAD

**Issue by hyejinie** [raycast/extensions#14630]
### Extension

https://raycast.com/mattisssa/spotify-player

### Raycast Version

1.83.1

### macOS Version

Sequoia 15.0

### Description

I'm using the spotify extension and raycast shortcut to play/pause. It says "bad gateway" upon first using the shortcut to toggle play, but if I use it a second time it plays. However, it is unable to toggle pause. 

Gets this:
#### Error:
```
Error: Bad gateway.
    at d4 (/Users/aria/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/nowPlaying.js:58:9011)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/Users/aria/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/nowPlaying.js:60:299)
```

### Steps To Reproduce

Using option + space as a shortcut to toggle play/pause. option+space once = 'bad gateway'. option+space again = toggles play. option+space a third time to toggle pause = 'bad gateway' and does not pause. Further option+space leads to the same result (i.e., unable to pause).

### Current Behaviour

Unable to toggle pause; able to toggle play but after 2 commands and with 'bad gateway' popping up.

### Expected Behaviour

Able to toggle play/pause.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by dxfan227** [comment]
Not sure if appropriate to add to this or open my own?  Similar behavior but when utilizing the menu bar GUI. Play/Pause results in "Bad Gateway" . Next/Previous results in " Payer Command Failed: No Active Device Found"

**Comment by jpsirois** [comment]
I also started been getting this from time to time lately. I've tried to sign out and sign in the extension without success. I restarted my Spotify app and it started working again.

**Comment by hyejinie** [comment]
It seems like both play/pause toggles correctly for me now. However, on the 'now playing' interface (which I also use to toggle play/pause), it doesn't update upon toggling. I.e., upon toggling pause, the music does pause, but the command prompt still reads 'pause' rather than 'play'. Subsequent command to 'pause' causes an 'error, please reload' screen. Upon reloading, the toggle resets and shows the correct command prompt 'play'.
