### ISSUE TITLE
[Set Audio Device] Unable to get output device list

### ISSUE THREAD

**Issue by like-aiquan** [raycast/extensions#14713]
### Extension

https://raycast.com/benvp/audio-device

### Raycast Version

1.83.1

### macOS Version

15.0

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set devices to {}

    tell application "System Preferences"
      reveal pane id "com.apple.preference.sound"
    end tell
    tell application "System Events"
      tell application process "System Preferences"
        repeat until exists tab group 1 of window "Sound"
        end repeat
        tell tab group 1 of window "Sound"
          click radio button "Output"
          tell table 1 of scroll area 1
            set selected_row to (first UI element whose selected is true)
            set currentOutput to value of text field 1 of selected_row as text
            
            repeat with r in rows
              try
                set deviceName to value of text field 1 of r as text
                set deviceType to value of text field 2 of r as text
                set end of devices to { deviceName, deviceType }
              end try
            end repeat
          end tell
        end tell
      end tell
    end tell

    if application "System Preferences" is running then
      tell application "System Preferences" to quit
    end if
    
    return [ devices, "currentOutput", currentOutput ]
   
64:116: execution error: “System Settings”遇到一个错误：不能获得“pane id "com.apple.preference.sound"”。 (-1728)
    at D9 (/Users/.../.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:4:57)
    at /Users/.../.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:4:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fa (/Users/.../.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:38:6806)
    at async N0 (/Users/.../.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:38:6981)
```
### 

### Steps To Reproduce

Just install extension and run "Set Output Device"

**Comment by like-aiquan** [comment]
I can't confirm if it's a problem with the MacOS system. After I restarted the computer, the plugin can be used normally. Amazing....
I will close this issue. Thanks.
