### ISSUE TITLE
[Apple Notes]...

### ISSUE THREAD

**Issue by AndrewDane** [raycast/extensions#15098]
### Extension

https://raycast.com/raycast/apple-notes

### Raycast Version

1.84.3

### macOS Version

15.0.1

#### Error:
```
Error: Command failed with exit code 1: osascript
9932:9933: syntax error: Expected “"” but found unknown token. (-2741)
    at Ah (/Users/dailywire/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/add-text.js:32:3080)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onSubmit [as current] (/Users/dailywire/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/add-text.js:126:12)
    at async /Users/dailywire/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/add-text.js:13:1139
    at async /Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:6111
```

### Steps To Reproduce

Add Text to Note -> Cmd+Enter -> error ^

### Current Behaviour

Error ^

### Expected Behaviour

Expected to append a selected note

**Comment by AndrewDane** [comment]
It seems like it has been fixed.  Thank you.
