### ISSUE TITLE
[GitHub] Github extension can not read org repo's

### ISSUE THREAD

**Issue by sailingbonbini** [raycast/extensions#15196]
### Extension

https://raycast.com/raycast/github

### Raycast Version

1.84.7

### macOS Version

14.5

#### Error:
```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `DE33:1E1AD3:1A707DDB:1ACF5728:6724B136` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `DE33:1E1AD3:1A707DDB:1ACF5728:6724B136` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  pushedAt\n  stargazerCount\n  isArchived\n  isFork\n  isPrivate\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:Doist archived:false sort:updated-desc","numberOfItems":100}}}
    at v6 (/Users/tom/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:241:85011)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tom/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:1257:1914
```

### Steps To Reproduce

1. Create Github Personal Access token with required permissions
2. Install Github Extensions
3. Authorize Github Extension in Github OAuth Apps
4. Configure Github Personal Access token in Raycast Extension
5. Use create issue command

### Current Behaviour

The dropdown does not contain any repositories, I can't create an issue

### Expected Behaviour

The dropdown contains a list of repositories, and I can create an issue from the extension.

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
