### ISSUE TITLE
[Spotify Player]... adding to Queue does not work

### ISSUE THREAD

**Issue by 4IngoJ** [raycast/extensions#15521]
### Extension

https://raycast.com/mattisssa/spotify-player

### Raycast Version

1.18.0

#### Error:
```
Error: Player command failed: No active device found
    at ia (/Users/ingojurz/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/generatePlaylist.js:44:5390)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i (/Users/ingojurz/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/generatePlaylist.js:72:1279)
```

### Steps To Reproduce

generate playlist, when playlist is presented, click add add songs to queue
![image](https://github.com/user-attachments/assets/459b6eb1-9182-402b-ab44-5451de2db480)

**Comment by thomaslombart** [comment]
This is happening for me when Spotify isn't currently playing music on a device. While the error message could be improved, this seems to be the right behaviour. Is it the same for you?

**Comment by 4IngoJ** [comment]
Ok, you’re right but i only works when the music plays on internal device speakers. I listen to the music on my sonos speakers, selecting them in the spotify app. When i have selected sonos speakers, the "Add to queue" option does not work.

Is this something to consider adding in the future?

￼

**Comment by thomaslombart** [comment]
I guess it would mean that Spotify doesn't recognize your Sonos speakers as an active device? I'm not sure we can do anything on our end if that's on Spotify's API end 😕
