### ISSUE TITLE
[World Clock]...

### ISSUE THREAD

**Issue by 0xdhrv** [raycast/extensions#15629]
### Extension

https://raycast.com/koinzhang/world-clock

### Raycast Version

1.86.1

### macOS Version

15.2

#### Error:
```
Error: read ECONNRESET
    at Si.from (/Users/dsuthar/.config/raycast/extensions/572bb8a7-8e3d-466e-a8ac-ff1b6d9b964b/query-world-time.js:36:25872)
    at xe.<anonymous> (/Users/dsuthar/.config/raycast/extensions/572bb8a7-8e3d-466e-a8ac-ff1b6d9b964b/query-world-time.js:39:8865)
    at xe.emit (node:events:519:28)
    at xe.emit (node:domain:488:12)
    at As.<computed> (/Users/dsuthar/.config/raycast/extensions/572bb8a7-8e3d-466e-a8ac-ff1b6d9b964b/query-world-time.js:36:887)
    at ClientRequest.emit (node:events:519:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at Vi.request (/Users/dsuthar/.config/raycast/extensions/572bb8a7-8e3d-466e-a8ac-ff1b6d9b964b/query-world-time.js:41:1926)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i3 (/Users/dsuthar/.config/raycast/extensions/572bb8a7-8e3d-466e-a8ac-ff1b6d9b964b/query-world-time.js:42:4956)
```

### Steps To Reproduce

1. Run the world clock query time extension

**Comment by koinzhang** [comment]
@0xdhrv Thanks for the feedback, since the extension originally used the World Time API in an unavailable state, it was changed to use the TimeAPI to query the time.
Fixing this issue in PR #16495 and waiting for merge-in to get the extension back in service.

**Comment by koinzhang** [comment]
@raycastbot close this issue
