### ISSUE TITLE
[Browser Bookmarks]can‘t search bookmarks for Chrome

### ISSUE THREAD

**Issue by jarviszhb** [raycast/extensions#16035]
### Extension

https://raycast.com/raycast/browser-bookmarks

### Raycast Version

1.88.4

### macOS Version

15.1.1

### Description

I was able to use this extension on Edge and Safari, but one day it stopped working on Chrome.

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'path')
    at c5 (/Users/jarvis/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:38:50743)
    at async /Users/jarvis/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:38:51042
```

### Steps To Reproduce

<img width="479" alt="image" src="https://github.com/user-attachments/assets/69d8a8c3-2ac3-481e-8235-12643ff0832a" />

**Comment by zhsks311** [comment]
Have you signed in to Chrome or created a default profile? If not, this issue could occur.

**Comment by jarviszhb** [comment]
> Have you signed in to Chrome or created a default profile? If not, this issue could occur.

1. I have signed in to Chrome using my Google account.
2. Are you asking whether to create a default profile in Chrome or Raycast? If so, I am not sure how to do this.
3. The issue occurred suddenly; previously, I was able to use this extension to search bookmarks in Chrome.

**Comment by jaehwi-kim-kurly** [comment]
> 2. Are you asking whether to create a default profile in Chrome or Raycast? If so, I am not sure how to do this.

Ah, by "Default" I was asking if you had created a profile without logging in at first.

Your issue appears to be a case where the Bookmarks file cannot be found.
Have you recently created or deleted any profiles?

Let's fix this step by step.
1. Navigate to /Users/{USER_NAME}/Library/Application Support/Google/Chrome directory and check if there are directories named Default, Profile {number}(like 1, 2, 3...)

2. We need to verify the profiles currently in use in Chrome.
  The file structure should look like this:
```
{
  "accessibility": ....,
  ....,
  "profile": {
   "info_cache": {
     "Default": {
       "name": "actual profile name",
       "gaia_name": "Google account name (if exists)",
       ...
     },
     "Profile 2": {
       "name": "actual profile name",
       "gaia_name": "Google account name (if exists)",
       ...
     },
     ...,,
    }
  }
}
```
Please check if Profile {numbers} and Default exist here.
3. Access the directory: /Users/{USER_NAME}/Library/Application Support/com.raycast.macos/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/com.raycast.api.cache

4. Open the journal file.

5. Copy the {String block} from "Chrome-profile {String block} number"

6. Check for a file named {String block} in com.raycast.api.cache

7. Inside, you'll find either Default or Profile {number} written. Please change this information to match the profile information (Default, Profile {number}) you verified in step 2. For the most reliable solution, I recommend first changing it to the profile you're currently using.

![image](https://github.com/user-attachments/assets/024f4517-7b0b-44eb-a3c3-e77c0c2aa38a)
![image](https://github.com/user-attachments/assets/e8521bfd-0259-4889-8c9b-4c3d743bff26)

**Comment by zhsks311** [comment]
> 2. Are you asking whether to create a default profile in Chrome or Raycast? If so, I am not sure how to do this.

Ah, by "Default" I was asking if you had created a profile without logging in at first.

Your issue appears to be a case where the Bookmarks file cannot be found.
Have you recently created or deleted any profiles?

Let's fix this step by step.
1. Navigate to /Users/{USER_NAME}/Library/Application Support/Google/Chrome directory and check if there are directories named Default, Profile {number}(like 1, 2, 3...)

2. We need to verify the profiles currently in use in Chrome.
  The file structure should look like this:
```
{
  "accessibility": ....,
  ....,
  "profile": {
   "info_cache": {
     "Default": {
       "name": "actual profile name",
       "gaia_name": "Google account name (if exists)",
       ...
     },
     "Profile 2": {
       "name": "actual profile name",
       "gaia_name": "Google account name (if exists)",
       ...
     },
     ...,,
    }
  }
}
```
Please check if Profile {numbers} and Default exist here.

3. Access the directory: /Users/{USER_NAME}/Library/Application Support/com.raycast.macos/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/com.raycast.api.cache

4. Open the journal file.

5. Copy the {String block} from "Chrome-profile {String block} number"

6. Check for a file named {String block} in com.raycast.api.cache

7. Inside, you'll find either Default or Profile {number} written. Please change this information to match the profile information (Default, Profile {number}) you verified in step 2. For the most reliable solution, I recommend first changing it to the profile you're currently using.

![image](https://github.com/user-attachments/assets/024f4517-7b0b-44eb-a3c3-e77c0c2aa38a)
![image](https://github.com/user-attachments/assets/e8521bfd-0259-4889-8c9b-4c3d743bff26)

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/15895, so I'll mark it as such.
