### ISSUE TITLE
[Hypersonic] Failed to fetch latest data

### ISSUE THREAD

**Issue by Nosrob** [raycast/extensions#2977]
# Extension – [Hypersonic](https://github.com/raycast/extensions/tree/b7cfd7b5d8dab3c3e0af5613b3da9236f3f3075f/extensions/hypersonic/)
Author: reboot.studio

## Description
After updating Hypersonic to its latest version, the connection with Notion seems to be broken and it can no longer retrieve my task list.

## Steps To Reproduce
IIn my case the problem appeared after the last update of the extension, I don't know if there are other elements necessary to reproduce it.

## The current behavior

My Todo list can't be fetched from Notion :

<img width="862" alt="Screenshot 2022-09-21 at 17 04 56@2x" src="https://user-images.githubusercontent.com/625348/191542055-4e7cc978-879a-4cae-8452-ab9a46c2d101.png">

The logs : 
```
Error: Status or checkbox property not found, please check your preferences
    at SE (/Users/nicolas/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:84:7292)
    at async Object.Zc.initialData (/Users/nicolas/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:84:8072)

```

So far I have tried :

- Uninstalling/reinstalling Hypersonic extension
- Logout from Notion then login again
- Granting access to my Notion database again
- Set up a new database in Notion

### Raycast version
1.39.3

**Comment by Nosrob** [comment]
I fixed the problem on my side by adding a Status property in my Notion database for Hypersonic, the newest version of the extension relies on that to know if an item is started or done. I'm actually not sure what reboot.studio's team can do about it, the Notion template has to be kept updated along with Raycast's extension at all times.
