### ISSUE TITLE
[Hypersonic] failing to fetch data

### ISSUE THREAD

**Issue by Michael-Choi** [raycast/extensions#4502]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

TypeError: Cannot read properties of undefined (reading 'forEach')
    at FC (/Users/michaelchoi/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:58:82744)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YC.initialData (/Users/michaelchoi/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:58:82924)

**Comment by Michael-Choi** [comment]
Resolved needed to add label as an optional property.
Labels seems to have been fixed by this update 🎉
![Screen Shot 2023-01-30 at 10 13 27 AM](https://user-images.githubusercontent.com/50688571/215516265-5ac7ece5-06b7-4125-8736-bed2116a32a5.png)
