### ISSUE TITLE
[GitHub] My Pull Requests doesn't load

### ISSUE THREAD

**Issue by pernielsentikaer** [raycast/extensions#4902]
### Extension

https://www.raycast.com/raycast/github

### Description

The command stops with an error:

![Raycast-4sDxlaYb@2x](https://user-images.githubusercontent.com/38033107/220382189-31db1134-e4be-4ba2-a4ea-9148938b882d.png)

```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `EBA1:18C2:1546CA:2B5F53:63F4D75E` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `EBA1:18C2:1546CA:2B5F53:63F4D75E` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query myPullRequests($createdOpenQuery: String!, $createdClosedQuery: String!, $assignedOpenQuery: String!, $assignedClosedQuery: String!, $mentionedOpenQuery: String!, $mentionedClosedQuery: String!, $reviewRequestsOpenQuery: String!, $reviewRequestsClosedQuery: String!, $reviewedByOpenQuery: String!, $reviewedByClosedQuery: String!, $numberOfOpenItems: Int!, $numberOfClosedItems: Int!) {\n  createdOpen: search(\n    query: $createdOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  createdClosed: search(\n    query: $createdClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  assignedOpen: search(\n    query: $assignedOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  assignedClosed: search(\n    query: $assignedClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  mentionedOpen: search(\n    query: $mentionedOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  mentionedClosed: search(\n    query: $mentionedClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewRequestsOpen: search(\n    query: $reviewRequestsOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewRequestsClosed: search(\n    query: $reviewRequestsClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewedByOpen: search(\n    query: $reviewedByOpenQuery\n    type: ISSUE\n    first: $numberOfOpenItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n  reviewedByClosed: search(\n    query: $reviewedByClosedQuery\n    type: ISSUE\n    first: $numberOfClosedItems\n  ) {\n    pullRequests: edges {\n      pullRequest: node {\n        ...PullRequestFields\n      }\n    }\n  }\n}\n\nfragment PullRequestFields on PullRequest {\n  id\n  title\n  permalink\n  merged\n  number\n  isDraft\n  closed\n  updatedAt\n  mergeable\n  milestone {\n    id\n    title\n  }\n  reviewDecision\n  repository {\n    ...ShortRepositoryFields\n  }\n  headRefName\n  headRef {\n    name\n  }\n  author {\n    ... on Bot {\n      id\n      login\n      avatarUrl(size: 64)\n    }\n    ... on User {\n      ...UserFields\n    }\n    ... on Mannequin {\n      id\n      login\n      avatarUrl(size: 64)\n    }\n    ... on Organization {\n      id\n      login\n      name\n      avatarUrl(size: 64)\n    }\n    ... on EnterpriseUserAccount {\n      id\n      login\n      name\n      avatarUrl(size: 64)\n    }\n  }\n  comments(first: 0) {\n    totalCount\n  }\n  reviewThreads(first: 100) {\n    totalCount\n    nodes {\n      comments(first: 0) {\n        totalCount\n      }\n    }\n  }\n  reviews(first: 100) {\n    totalCount\n    nodes {\n      bodyText\n    }\n  }\n  commits(last: 1) {\n    nodes {\n      commit {\n        statusCheckRollup {\n          state\n        }\n      }\n    }\n  }\n  assignees(first: 50) {\n    totalCount\n    nodes {\n      ... on User {\n        ...UserFields\n      }\n    }\n  }\n}\n\nfragment ShortRepositoryFields on Repository {\n  id\n  defaultBranchRef {\n    target {\n      oid\n    }\n  }\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n}\n\nfragment UserFields on User {\n  id\n  avatarUrl\n  name\n  login\n  isViewer\n}","variables":{"createdOpenQuery":"is:pr author:@me archived:false is:open updated:>2023-02-07 ","createdClosedQuery":"is:pr author:@me archived:false is:closed updated:>2023-02-07 ","assignedOpenQuery":"is:pr assignee:@me archived:false is:open updated:>2023-02-07 ","assignedClosedQuery":"is:pr assignee:@me archived:false is:closed updated:>2023-02-07 ","mentionedOpenQuery":"is:pr mentions:@me archived:false is:open updated:>2023-02-07 ","mentionedClosedQuery":"is:pr mentions:@me archived:false is:closed updated:>2023-02-07 ","reviewRequestsOpenQuery":"is:pr review-requested:@me archived:false is:open updated:>2023-02-07 ","reviewRequestsClosedQuery":"is:pr review-requested:@me archived:false is:closed updated:>2023-02-07 ","reviewedByOpenQuery":"is:pr reviewed-by:@me archived:false is:open updated:>2023-02-07 ","reviewedByClosedQuery":"is:pr reviewed-by:@me archived:false is:closed updated:>2023-02-07 ","numberOfOpenItems":20,"numberOfClosedItems":20}}}
    at /Users/pernielsentikaer/.config/raycast-internal/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:95:22017
    at p (/Users/pernielsentikaer/.config/raycast-internal/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:95:16030)
    at Object.next (/Users/pernielsentikaer/.config/raycast-internal/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:95:15334)
    at l (/Users/pernielsentikaer/.config/raycast-internal/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:95:14892)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

I just installed it from the store and connected it to GitHub

**Comment by thomaslombart** [comment]
That typically happens when you have lots of pull requests. Is it the case for you? Maybe you have too many PRs?
