### ISSUE TITLE
[ray.so] Characters not showing correctly

### ISSUE THREAD

**Issue by moisesrodriguez** [raycast/extensions#5054]
### Extension

https://www.raycast.com/garrett/ray-so

### Description

When I use **Create Image From Code** it does not show the code correctly

### Steps To Reproduce

1. Open Create Image From Code
2. Paste code
3. Create Snippet
4. View Snippet in Browser

Code used:

```
docker compose up

[+] Running 3/2
 ⠿ Network backend-4rso_server-side  Created                                                                                                                                                                          0.0s
 ⠿ Container db                      Created                                                                                                                                                                          0.0s
 ⠿ Container backend                 Created                                                                                                                                                                          0.1s
Attaching to backend, db
db       | 2023-03-01 00:05:25+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
db       | 2023-03-01 00:05:25+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db       | 2023-03-01 00:05:25+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
backend  | DATABASE_URL: mysql://root:xxxxxx@db:3303/taxes
backend  | ROCKET_DATABASES: {mysql={url="mysql://root:xxxxxxx@db:3303/taxes"}}
db       | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db       | 2023-03-01T00:05:26.483457Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
db       | 2023-03-01T00:05:26.483472Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
db       | 2023-03-01T00:05:26.488067Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
db       | 2023-03-01T00:05:26.506747Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db       | 2023-03-01T00:05:26.795074Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db       | 2023-03-01T00:05:26.924221Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db       | 2023-03-01T00:05:26.924324Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db       | 2023-03-01T00:05:26.926829Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db       | 2023-03-01T00:05:26.943430Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db       | 2023-03-01T00:05:26.943639Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
backend  | Error: database pool init error for pool named `mysql`
backend  |    >> timed out waiting for connection: Can't connect to MySQL server on 'db' (115)
backend  | Error: Rocket failed to launch due to failing fairings:
backend  |    >> 'mysql' Database Pool
backend  | thread 'main' panicked at 'aborting due to fairing failure(s)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:229:17
backend  | stack backtrace:
backend  |    0: rust_begin_unwind
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
backend  |    1: core::panicking::panic_fmt
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
backend  |    2: <rocket::error::Error as core::ops::drop::Drop>::drop
backend  |    3: tokio::runtime::park::CachedParkThread::block_on
backend  |    4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
backend  |    5: tokio::runtime::runtime::Runtime::block_on
backend  |    6: rocket::async_main
backend  |    7: backend_4rso::main
backend  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
backend exited with code 101
backend  | thread 'main' panicked at 'aborting due to fairing failure(s)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:229:17
backend  | stack backtrace:
backend  | Error: database pool init error for pool named `mysql`
backend  |    >> timed out waiting for connection: Can't connect to MySQL server on 'db' (115)
backend  | Error: Rocket failed to launch due to failing fairings:
backend  |    >> 'mysql' Database Pool
backend  |    0: rust_begin_unwind
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
backend  |    1: core::panicking::panic_fmt
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
backend  |    2: <rocket::error::Error as core::ops::drop::Drop>::drop
backend  |    3: tokio::runtime::park::CachedParkThread::block_on
backend  |    4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
backend  |    5: tokio::runtime::runtime::Runtime::block_on
backend  |    6: rocket::async_main
backend  |    7: backend_4rso::main
backend  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
backend exited with code 101
backend  | Error: database pool init error for pool named `mysql`
backend  |    >> timed out waiting for connection: Can't connect to MySQL server on 'db' (115)
backend  | Error: Rocket failed to launch due to failing fairings:
backend  |    >> 'mysql' Database Pool
backend  | thread 'main' panicked at 'aborting due to fairing failure(s)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:229:17
backend  | stack backtrace:
backend  |    0: rust_begin_unwind
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
backend  |    1: core::panicking::panic_fmt
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
backend  |    2: <rocket::error::Error as core::ops::drop::Drop>::drop
backend  |    3: tokio::runtime::park::CachedParkThread::block_on
backend  |    4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
backend  |    5: tokio::runtime::runtime::Runtime::block_on
backend  |    6: rocket::async_main
backend  |    7: backend_4rso::main
backend  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
backend exited with code 101
backend  | Error: database pool init error for pool named `mysql`
backend  |    >> timed out waiting for connection: Can't connect to MySQL server on 'db' (115)
backend  | Error: Rocket failed to launch due to failing fairings:
backend  |    >> 'mysql' Database Pool
backend  | thread 'main' panicked at 'aborting due to fairing failure(s)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/error.rs:229:17
backend  | stack backtrace:
backend  |    0: rust_begin_unwind
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
backend  |    1: core::panicking::panic_fmt
backend  |              at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
backend  |    2: <rocket::error::Error as core::ops::drop::Drop>::drop
backend  |    3: tokio::runtime::park::CachedParkThread::block_on
backend  |    4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
backend  |    5: tokio::runtime::runtime::Runtime::block_on
backend  |    6: rocket::async_main
backend  |    7: backend_4rso::main
backend  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
backend exited with code 101
```

### Current Behaviour

This is how it looks when I use the extension
![CleanShot 2023-02-28 at 18 06 34](https://user-images.githubusercontent.com/3869040/222011676-f3a98d8b-3344-4081-a860-7e73b0be2516.png)

### Expected Behaviour

This is how it looks when I paste it directly into the website
![CleanShot 2023-02-28 at 18 06 51](https://user-images.githubusercontent.com/3869040/222011752-d58109b3-5c86-43c7-996b-2e177c1856d8.png)

**Comment by moisesrodriguez** [comment]
At first, I thought it was that code, but all code has the same issue.
![CleanShot 2023-03-01 at 17 08 12](https://user-images.githubusercontent.com/3869040/222287393-c8a551db-a383-4e3b-8849-ee3661ee55cf.png)

code: 
```
let listNotarialInstructions = [];         const years = [moment().year()-1, moment().year(), moment().year()+1];         try {             const begin = Date.now();             listNotarialInstructions = await this.notarialInstructionRepository.find({                 select: ['requestId'], skip, take,                 where: (qb: SelectQueryBuilder<NotarialInstructionEntity>) => {                     qb.where('notarial_process_status_id != 3')                     qb.andWhere('credit_status_id != 12')                     qb.andWhere('fovi_id is not null')                     qb.andWhere('fovi_id != 0')                     if (!!notarialInstructionStatusId) {                         qb.andWhere('notarial_process_status_id in (:notarialInstructionStatusId)', {notarialInstructionStatusId});                         qb.andWhere('program in (:years)', {years});                     }                 }             });             const end = Date.now();             timeFindNI += (end - begin) / 1000;         } catch (error) {             this.logger.error(`NotarialInstructionServiceImpl::updatePhasesNotarialInstruction`);             this.logger.error(error);             throw new InternalServerErrorException("Error al buscar listado de Instrucciones notariales");         }
```

**Comment by moisesrodriguez** [comment]
I just checked and the issue persists.

**Comment by RSO** [comment]
This turned out to be a Base64 serialization issue. I fixed it by replacing `Buffer.from(code.snippet).toString("base64")` to using the `js-base64` package's `encodeURI`, which seems safer to use in URLs!
