### ISSUE TITLE
[Arc]...

### ISSUE THREAD

**Issue by zacfire** [raycast/extensions#5292]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Arc"
      return version
    end tell
   
osascript: can't open default scripting component.
    at h8 (/Users/zac/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:57)
    at /Users/zac/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:8086
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Vp (/Users/zac/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:41339)
    at async Object.R0 [as current] (/Users/zac/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:64:63)
```

**Comment by thomaspaulmann** [comment]
That's an odd one. Can you check if you are on the latest version of Arc?
