### ISSUE TITLE
[BetterTouchTool]...Error: Command was killed with null

### ISSUE THREAD

**Issue by ttym572** [raycast/extensions#5346]
### Extension

https://raycast.com/dnnsmnstrr/bettertouchtool

#### Error:
```
Error: Command was killed with null: osascript -l JavaScript -e function run(argv) {
    let BetterTouchTool = Application('BetterTouchTool');
    return BetterTouchTool.get_triggers({trigger_id: 643 });
  } run();
execution error: Error: Error: 信息无法识别。 (-1708)
    at s4 (/Users/ttym/.config/raycast/extensions/bb1e5e21-0827-4c47-88af-ab498770f9b0/trigger.js:12:57)
    at Object.o4 [as current] (/Users/ttym/.config/raycast/extensions/bb1e5e21-0827-4c47-88af-ab498770f9b0/trigger.js:12:310)
    at Object.current (/Users/ttym/.config/raycast/extensions/bb1e5e21-0827-4c47-88af-ab498770f9b0/trigger.js:12:1115)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dnnsmnstrr** [comment]
I'll have a look at this, it might be related to the problems in https://github.com/dnnsmnstrr/alfred-btt/issues/2

**Comment by dnnsmnstrr** [comment]
Possible fix: https://github.com/raycast/extensions/pull/6458

**Comment by dnnsmnstrr** [comment]
Hopefully this problem is resolved, let's close the issue for now...

@raycastbot close this issue
