### ISSUE TITLE
[Music]: doesn't add to library / playlist

### ISSUE THREAD

**Issue by kolchurinvv** [raycast/extensions#5915]
### Extension

https://raycast.com/fedevitaledev/music

### Description

using the extensions' ability to add to a playlist or to a library doesn't do anything and only shows the (I assume) a bit broken notification overlay 
<img width="256" alt="Screenshot 2023-04-12 at 14 26 51" src="https://user-images.githubusercontent.com/18503099/231573742-8051823c-09de-4561-9e0a-40f04a9bcabc.png">
it is a repeat of #5344 , but still happens on my mac
![Screenshot 2023-04-12 at 22 17 57](https://user-images.githubusercontent.com/18503099/231575010-4983dd00-ddf5-4729-8dd3-3bfc331ef4f8.png)

### Steps To Reproduce

start listening to a song
try to add it to library or playlist

### Current Behaviour

shows overlay, but doesn't add anything to the library

### Expected Behaviour

to add song to the library and to the playlist, if that was the call

**Comment by Rawnly** [comment]
Hi @kolchurinvv thanks for opening this issue. I'm working on a new version of the extension integrated with the MusicKit api. 

While this behaviour can be frustrating I'd suggest to wait, and see if the new version fixes it.

**Comment by kolchurinvv** [comment]
hey! no problem at all! thanks for your efforts!

**Comment by Rawnly** [comment]
hey @kolchurinvv if you're interested you can try out the new upcoming version [here](https://github.com/rawnly/raycast-music)

**Comment by kolchurinvv** [comment]
yeah, i'll check it out over the weekend

**Comment by kolchurinvv** [comment]
@Rawnly, I'm playing around with it right now. Found an issue with trying to play a song from recently played.
the terminal logs:
```bash
10:29:33.604 [FmdIY] GET - https://api.music.apple.com/v1/catalog/us/search?term=Unobsidian+Kx5&types=songs&limit=25
10:29:33.715 [tpIUP] 200 - OK]
10:29:33.718 {
  id: 15528,
  name: 'Unobsidian',
  artist: 'Kx5, deadmau5 & Kaskade',
  album: 'Kx5',
  duration: '371,544006347656',
  rating: 0,
  loved: false,
  disliked: false
}
10:29:34.050 [JFlgA] 200 - OK]
10:29:34.057 {
  id: 15528,
  name: 'Unobsidian',
  artist: 'Kx5, deadmau5 & Kaskade',
  album: 'Kx5',
  duration: '371,544006347656',
  rating: 0,
  loved: false,
  disliked: false
}
10:29:34.179 [FmdIY] 200 - OK]
10:29:34.188 {
  id: 15528,
  name: 'Unobsidian',
  artist: 'Kx5, deadmau5 & Kaskade',
  album: 'Kx5',
  duration: '371,544006347656',
  rating: 0,
  loved: false,
  disliked: false
}
10:29:34.188 {
  id: 15528,
  name: 'Unobsidian',
  artist: 'Kx5, deadmau5 & Kaskade',
  album: 'Kx5',
  duration: '371,544006347656',
  rating: 0,
  loved: false,
  disliked: false
}
10:29:35.427 [eX_0c] GET - https://api.music.apple.com/v1/me/storefront
10:29:35.450 Warning: Failed prop type: The prop `keywords[1]` is marked as required in `List.Item`, but its value is `undefined`.
    at Cn (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:17899)
    at PerformAction (/Users/vladimir/.config/raycast/extensions/music/quick-actions.js:36366:24)
    at ray-action-panel
    at gt (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:5734)
    at ray-list-item
    at Cn (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:17899)
    at Or (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:5486)
    at ray-list
    at lt (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:19621)
    at QuickActions (/Users/vladimir/.config/raycast/extensions/music/quick-actions.js:36148:84)
    at Er (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:2490)
    at ray-navigation-stack
    at _o (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:2088)
    at Suspense
    at Tr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:4:4691)
    at ray-root
    at ri (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:3000)
10:29:35.495 [RQhdo] GET - https://api.music.apple.com/v1/me/recommendations
10:29:35.500 [aTEzc] GET - https://api.music.apple.com/v1/me/recent/played/tracks?types=library-songs%2Csongs
10:29:35.575 [vn3Jj] GET - https://api.music.apple.com/v1/me/storefront
10:29:35.579 [eX_0c] 200 - OK]
10:29:35.816 [vn3Jj] 200 - OK]
10:29:35.841 [aTEzc] 200 - OK]
10:29:35.957 [RQhdo] 200 - OK]
10:29:37.092 [-4eWd] GET - https://api.music.apple.com/v1/me/recent/played/tracks?types=library-songs%2Csongs
10:29:37.156 [inQ56] GET - https://api.music.apple.com/v1/me/storefront
10:29:37.307 [inQ56] 200 - OK]
10:29:37.590 [-4eWd] 200 - OK]
10:29:37.823 View pushed recently-played
10:29:42.715
Error: missing expected parameter: path

process.processImmediate:timers:471:21
```
the authentication went fine by the way.

**Comment by kolchurinvv** [comment]
the "add to library works" though. just tested. Q: wasn't there an action to add to a specific playlist before? Would be really cool to be able to do that

**Comment by Rawnly** [comment]
Hi @kolchurinvv can you open an issue in the related project? In order to track it correctly.

> Q: I can't seem to find the "add to playlist" action. has it been removed?

I'm still working on this. Unfortunately this week I've been really busy :(
