### ISSUE TITLE
[Hypersonic] Can't retrieve tasks

### ISSUE THREAD

**Issue by jrochelle** [raycast/extensions#6591]
### Extension

https://raycast.com/reboot/hypersonic

### Description

First let me say, this is stunningly cool, I really want to get this working nice job.

#### Error:
```
TypeError: Cannot read properties of undefined (reading '0')
    at D2 (/Users/jrochelle/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:89956)
    at /Users/jrochelle/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90671
    at Array.map (<anonymous>)
    at KC (/Users/jrochelle/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90664)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ZC.initialData (/Users/jrochelle/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90770)
```

### Steps To Reproduce

1. Authenticated with Notion
2. Allowed access to 2 databases named Tasks and Projects
3. PROBLEM: When trying to retrieve tasks in raycast, I get the attached error.
4. Notably, I can insert new tasks, but can't retrieve any to view or manage in raycast.

### Current Behaviour

When executing My Tasks in raycast, I get an error is displayed: Cannot read properties of undefined (reading '0') and no tasks are retrieved.

### Expected Behaviour

When executing My Tasks in raycast, I would get a list of tasks returned and displayed in the raycast UI.

**Comment by jrochelle** [comment]
This is still an issue. I may have to learn python and fix this one myself...really want this extension to work!
