### ISSUE TITLE
Integration with raycast

### ISSUE THREAD

**Issue by eddowding** [raycast/extensions#6756]
### Extension

https://raycast.com/reboot/hypersonic

#### Error:
```
TypeError: Cannot read properties of undefined (reading '0')
    at D2 (/Users/eddowding/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:89956)
    at /Users/eddowding/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90671
    at Array.map (<anonymous>)
    at KC (/Users/eddowding/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90664)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ZC.initialData (/Users/eddowding/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90770)
```

### Steps To Reproduce

d

**Comment by ambitendencies** [comment]
Same issue and would like a response so I'm not wasting my time with this extension if it's abanadoned.
