### ISSUE TITLE
Self Signed-in Certification error [Todoist]...

### ISSUE THREAD

**Issue by rishavs24** [raycast/extensions#7643]
### Extension

https://raycast.com/doist/todoist

#### Error:
```
Error: self-signed certificate in certificate chain
    at Qn.from (/Users/rishav.sethia/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:56:17861)
    at nt.<anonymous> (/Users/rishav.sethia/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:59:8717)
    at nt.emit (node:events:513:28)
    at nt.emit (node:domain:489:12)
    at q3.<computed> (/Users/rishav.sethia/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:35:729)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
```

### Steps To Reproduce

Once the extension is installed, when creating a new task or doing any task related to todoist using the extension, getting the above erorr.

**Comment by kud** [comment]
Hey @rishavs24, I can't reproduce the error. Could you please explain a bit more about the context?

**Comment by rishavs24** [comment]
Hey, trying to attach a video of the recreated issue, hope that will help. https://youtu.be/BNoikNFrFu8

**Comment by mathieudutour** [comment]
Are you using a proxy? A firewall? Did you configure the proxy settings in Raycast?

**Comment by rishavs24** [comment]
Hey,  I am on a company device and there is some official proxy installed on the laptop. Do you have any recommendation on how to configure the proxy settings within Raycast?

From: Mathieu Dutour ***@***.***>
Date: Wednesday, 8 November 2023 at 5:53 PM
To: raycast/extensions ***@***.***>
Cc: Rishav Sethia ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] Self Signed-in Certification error [Todoist]... (Issue #7643)
Caution: This email originated from outside the organization. Do not click any links or open attachment unless you recognize the sender and know the content is safe. Also check the email id of the sender carefully before any action.



Are you using a proxy? A firewall? Did you configure the proxy settings in Raycast?
