### ISSUE TITLE
[CodeSnap] Extension is broken

### ISSUE THREAD

**Issue by Jiralite** [raycast/extensions#7808]
### Extension

https://raycast.com/Mokkapps/codesnap

### Description

Just downloaded this now and tested on multiple devices and browsers (Safari, Google Chrome, etc.)... this extension just seems to be broken. Looking at the developer tools, there is an error:

```xl
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at pe (_id_.e58c350e.js:599:11888)
    at he (_id_.e58c350e.js:599:12246)
    at po (_id_.e58c350e.js:599:12515)
    at _id_.e58c350e.js:599:12988
    at entry.23149564.js:1:32531
    at ks (entry.23149564.js:1:14380)
    at Mr (entry.23149564.js:1:14459)
    at Sp.t.__weh.t.__weh (entry.23149564.js:1:32411)
    at $f (entry.23149564.js:1:15753)
    at C8 (entry.23149564.js:1:16060)
```

### Steps To Reproduce

1. Use it

### Current Behaviour

The extension does not work.

### Expected Behaviour

The extension works.

**Comment by Mokkapps** [comment]
@Jiralite thanks for reporting the problem, it is resolved!

@raycastbot close this issue
