### ISSUE TITLE
[Arc]...

### ISSUE THREAD

**Issue by Katherin4u** [raycast/extensions#8033]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set _output to ""

    tell application "Arc"    
      set _space_index to 1  
      
      repeat with _space in spaces of front window
        set _title to get title of _space
        
        set _output to (_output & "{ \"title\": \"" & _title & "\", \"id\": " & _space_index & " }")
        
        if _space_index < (count spaces of front window) then
          set _output to (_output & ",\n")
        else
          set _output to (_output & "\n")
        end if
        
        set _space_index to _space_index + 1
      end repeat
    end tell
    
    return "[\n" & _output & "\n]"
   
98:549: execution error: Not authorized to send Apple events to Arc. (-1743)
    at g8 (/Users/kathering/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:57)
    at /Users/kathering/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Cp (/Users/kathering/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:34:41326)
    at async Object.Ga [as current] (/Users/kathering/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:42:32)
```

### Steps To Reproduce

1: Open arc
2: Click on the arc Icon at the top right of the screen
3: Error given "Failed to fetch latest data"

**Comment by velios** [comment]
@Katherin4u Hi. Thanks for reporting. Can you upload some explanatory image or video. I try to reproduce, but don't understand which icon needs to be clicked.
