### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by isaquepereira** [raycast/extensions#8101]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)

### Steps To Reproduce

1. In Sonoma 14.0 Beta (23A5301h) and Raycast 1.57.2
2. Trying to run the command "Love track"

### Current Behaviour

Error: Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)
    at Cm (/Users/isaquepereira/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love.js:5:59)
    at /Users/isaquepereira/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love.js:5:10465
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async su (/Users/isaquepereira/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love.js:5:40086)

### Expected Behaviour

Love the track and show a feedback about it.

**Comment by rawnly** [comment]
duplicate of #7852

**Comment by rawnly** [comment]
@raycastbot close this issue
