### ISSUE TITLE
[Music] Bug when add music to library

### ISSUE THREAD

**Issue by Chivier** [raycast/extensions#8652]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

I use raycast apple music, 'love and add to library'. it reports an unexpected error

### Steps To Reproduce

(I guess this bug happens on macOS Sonoma)
1. update system to macOS Sonoma
2. open apple music
3. use raycast apple music, love and add to library

### Current Behaviour

Error: Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)
    at Lm (/Users/chivier/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love-and-add-to-library.js:5:59)
    at /Users/chivier/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love-and-add-to-library.js:5:10465
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lu (/Users/chivier/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/love-and-add-to-library.js:5:40097)

**Comment by rawnly** [comment]
#8648 fixes this 🙂
