### ISSUE TITLE
[Github] message: "Bad credentials"

### ISSUE THREAD

**Issue by Angelk90** [raycast/extensions#8984]
### Extension

https://www.raycast.com/raycast/github

### Description

I started the `Github` project, after starting it I get the following error:

```
[0] ready -  built extension successfully
[1] [STARTED] Parse Configuration
[1] [SUCCESS] Parse Configuration
[1] [STARTED] Generate outputs
[1] [STARTED] Generate to ./src/generated/graphql.ts
[1] [STARTED] Load GraphQL schemas
[1] [FAILED] 
[1] [FAILED]         Failed to load schema from https://api.github.com/graphql:
[1] [FAILED] 
[1] [FAILED]         Could not obtain introspection result, received the following as response; 
[1] [FAILED]  { message: "Bad credentials", documentation_url: "https://docs.github.com/graphql" }
[1] [FAILED]         GraphQLError: Could not obtain introspection result, received the following as response; 
[1] [FAILED]  { message: "Bad credentials", documentation_url: "https://docs.github.com/graphql" }
[1] [FAILED]     at createGraphQLError (/Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)
[1] [FAILED]     at getSchemaFromIntrospection (/Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/wrap/cjs/introspect.js:21:42)
[1] [FAILED]     at /Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/wrap/cjs/introspect.js:44:32
[1] [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] [FAILED]     at async UrlLoader.load (/Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/url-loader/cjs/index.js:220:29)
[1] [FAILED]     at async /Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
[1] [FAILED]     at async Promise.all (index 5)
[1] [FAILED]     at async loadFile (/Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
[1] [FAILED]     at async /Users/userName/Desktop/raycast/github/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:229:25
[1] [FAILED] 
[1] [FAILED]         GraphQL Code Generator supports:
[1] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[1] [FAILED]           - Introspection JSON File
[1] [FAILED]           - URL of GraphQL endpoint
[1] [FAILED]           - Multiple files with type definitions (glob expression)
[1] [FAILED]           - String in config file
[1] [FAILED] 
[1] [FAILED]         Try to use one of above options and run codegen again.
[1] [FAILED] 
[1] [FAILED]       
[1] [SUCCESS] Generate outputs
[1]   ℹ Watching for changes...
```

I added the token both from the settings settings and via the `.env.example` file which contains `GITHUB_TOKEN=`.

### Steps To Reproduce

1) Start the github project `npm run dev`

**Comment by thomaslombart** [comment]
Have you followed the steps of the `CONTRIBUTING.md` file in the `github` extension folder?

**Comment by thomaslombart** [comment]
Since you created a PR, I assumed you were able to make it work. Feel free to reopen the issue if you notice something wrong.
