### ISSUE TITLE
reason: connect ECONNREFUSED

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#9810]
### Extension

https://raycast.com/tonka3000/weather

#### Error:
```
Error: request to https://wttr.in/?format=j1 failed, reason: connect ECONNREFUSED 5.9.243.187:443
    at kd.fetch (/Users/skoro/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:37:10819)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async kd.getWeather (/Users/skoro/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:37:10912)
    at async Li.keepPreviousData (/Users/skoro/.config/raycast/extensions/c460fc92-202d-49bf-b9c4-e486b58a0189/index.js:37:15483)
```

### Steps To Reproduce

1. Open Raycast
2. Execute Weather command

### Current Behaviour

Shows this error

### Expected Behaviour

Shows the weather

**Comment by j3lte** [comment]
Nothing wrong with the extension: wttr.in seems to be down: https://github.com/chubin/wttr.in/issues/946

**Comment by romanskorobagatko** [comment]
It's working now.
