### ISSUE TITLE
[Spotify Player] I am always required to sign in 

### ISSUE THREAD

**Issue by sajeezy** [raycast/extensions#9988]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Everytime I try to use a command, it requires me to sign in. 
![CleanShot 2024-01-04 at 18 15 48](https://github.com/raycast/extensions/assets/3699393/20be521a-8632-4f73-ba98-5959d0709e8b)

### Steps To Reproduce

Download extension
Log in (authenticate)
Approve
Done
Next time i need to use command, it asks to authenticate again

**Comment by Evolinox** [comment]
> Hey, can you provide more details please? Steps to reproduce and/or a video recording? We are unable to reproduce.

I have been using the plugin the last four days and it required me to sign-in 5 Times already... I'm normally using my Mac and not touching anything related to the Plugin, however the red Cautionmark still pops up after a while 
<img width="195" alt="image" src="https://github.com/raycast/extensions/assets/72224389/e22dc790-7215-4963-9e27-f24de23857b1">

This is the Error, I am getting:
```json
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-02-02T15:51:37.828Z","data":{"function":"getApplications"}}]}: 
```
(Sorry for bad formatting :D)

**Comment by peduarte** [comment]
Oh ok, that's certainly not expected behaviour :/ is there anything else you could share, perhaps whether you're using a vpn? 

@sxn can you think of any reason why this may happen to this specific user?

**Comment by sxn** [comment]
not sure 🤔 @Evolinox what version of Raycast are you using? and – did the menu bar command work after you logged in? could you see the currently playing song for a while, only to then later have it stop working?

**Comment by Evolinox** [comment]
> Oh ok, that's certainly not expected behaviour :/ is there anything else you could share, perhaps whether you're using a vpn?
> 
> @sxn can you think of any reason why this may happen to this specific user?

Can't share much more, i think :/ I didn't use a VPN at all. 



> not sure 🤔 @Evolinox what version of Raycast are you using? and – did the menu bar command work after you logged in? could you see the currently playing song for a while, only to then later have it stop working?

I am currently using Version 1.66.2. The Menubar Command works fine for atleast an hour... when i come back to my Mac, it has logged out and displays the red danger icon. Maybe it has to do with the Standby Mode?

**Comment by peduarte** [comment]
I know that sometimes when I login after my laptop's been asleep, i see the reed triangle too while it's connecting to the wifi. but once it connects, it goes away and I dont need to sign in again. fwiw ive been using this extension for months. so this is so weird.

have you tried uninstalling the extension and installing it again?

**Comment by sajeezy** [comment]
Just wanted to circle back here. I travelled to a country where the Spotify service is not available – I could still use Spotify on my devices though, but the extension was forcing me to sign in. I have since returned to South Africa and its not caused me problems yet. So I will monitor it this week and report back.

**Comment by Evolinox** [comment]
> have you tried uninstalling the extension and installing it again?

Yes, ive done this twice already, but its still happening.

> I travelled to a country where the Spotify service is not available – I could still use Spotify on my devices though, but the extension was forcing me to sign in.

I'm from/in Germany, where Spotify is fully available afaik.

**Comment by cupcakearmy** [comment]
Same on my end unfortunately

**Comment by alivault** [comment]
I’ve noticed that it stays signed in if I enable “Hide icon when idle” in the settings for Menu Bar Player. It might be something to do with Oauth not being able to make requests in the background.

**Comment by alivault** [comment]
I retract my previous comment. "Hide icon when idle" doesn't seem to make a difference; the extension continues to log out at least once a day.

**Comment by flawnn** [comment]
Yeah, have the same issue.

**Comment by cupcakearmy** [comment]
> I’ve noticed that it stays signed in if I enable “Hide icon when idle” in the settings for Menu Bar Player. It might be something to do with Oauth not being able to make requests in the background.

For me... it seemed to resolve it. Since I disabled the "mane bar player" in the settings completely I've stayed logged in

**Comment by flawnn** [comment]
https://github.com/raycast/extensions/tree/4367e1f447712d070bfe44e5f2b9d4ad5b408cac/extensions/spotify-player/

This version works perfectly for me. Installed it locally and **with** the menu bar player everything works fine. There must be something broken in between then with the OAuth Configuration and the menu bar player.

**Comment by Joshua-Wilcox** [comment]
same issue here 👍🏻

**Comment by alivault** [comment]
Deactivating the menu bar player seems to solve the signing out problem.

**Comment by lucasmpramos** [comment]
any fixes to use the menu bar player?

**Comment by Evolinox** [comment]
> any fixes to use the menu bar player?

Nope, it still happens

**Comment by flawnn** [comment]
There is nothing to close here - This is still an issue. Please DON'T CLOSE!

**Comment by lucasmpramos** [comment]
No updates here guys?

I know this is non-profit. But this has been an issue for months now. Isn't it relatively easy to fix? 

Such a nice little feature – like everything else Raycast. 

Please fix

**Comment by Eldrick19** [comment]
Getting a similar issue. Commenting to follow, this has never happened until a week or so ago

**Comment by mattisssa** [comment]
I've noticed the same behavior for the past couple of weeks, but I'm not sure if it's connected to the extension 🤔

**Comment by danielraffel** [comment]
I am playing around with modifying the setSpotifyClient function to include a network check and retry logic. Rebuilt the plugin and installed it. It's been 24 hours and the plugin hasn't lost its Oauth token, so we'll see if this continues. FWIW this was a quick hack and I'm not convinced this is implemented correctly!

```
import { showHUD } from "@raycast/api";

export async function setSpotifyClient() {
  const isConnected = await checkNetworkConnectivity();
  if (!isConnected) {
    await showHUD("Network is not available. Please check your VPN connection.");
    return;
  }

  let retries = 3;
  while (retries > 0) {
    try {
      const accessToken = await provider.authorize();
      api.defaults.headers = {
        Authorization: `Bearer ${accessToken}`,
      };
      api.defaults.fetch = nodeFetch as any;
      spotifyClient = api;
      return;
    } catch (error) {
      console.error("Error during authentication:", error);
      retries--;
      if (retries === 0) {
        await showHUD("Failed to authenticate with Spotify. Please try again.");
        throw error;
      }
      await new Promise(resolve => setTimeout(resolve, 2000)); // Wait 2 seconds before retrying
    }
  }
}

async function checkNetworkConnectivity() {
  try {
    await fetch('https://api.spotify.com', { method: 'HEAD', mode: 'no-cors' });
    return true;
  } catch (error) {
    return false;
  }
}
```

**Comment by flawnn** [comment]
> I am playing around with modifying the setSpotifyClient function to include a network check and retry logic. Rebuilt the plugin and installed it. It's been 24 hours and the plugin hasn't lost its (freshly authorized) Oauth token, so we'll see if this continues. FWIW this was a quick hack and this is most def not implemented ideally! BTW the menu bar is enabled and working which was problematic before. Waiting for it to ask for Spotify auth again tho. lolz
> 
> ```
> import { showHUD } from "@raycast/api";
> 
> export async function setSpotifyClient() {
>   const isConnected = await checkNetworkConnectivity();
>   if (!isConnected) {
>     await showHUD("Network is not available. Please check your VPN connection.");
>     return;
>   }
> 
>   let retries = 3;
>   while (retries > 0) {
>     try {
>       const accessToken = await provider.authorize();
>       api.defaults.headers = {
>         Authorization: `Bearer ${accessToken}`,
>       };
>       api.defaults.fetch = nodeFetch as any;
>       spotifyClient = api;
>       return;
>     } catch (error) {
>       console.error("Error during authentication:", error);
>       retries--;
>       if (retries === 0) {
>         await showHUD("Failed to authenticate with Spotify. Please try again.");
>         throw error;
>       }
>       await new Promise(resolve => setTimeout(resolve, 2000)); // Wait 2 seconds before retrying
>     }
>   }
> }
> 
> async function checkNetworkConnectivity() {
>   try {
>     await fetch('https://api.spotify.com', { method: 'HEAD', mode: 'no-cors' });
>     return true;
>   } catch (error) {
>     return false;
>   }
> }
> ```
> 
> **24 Hour Update:** It’s still working. Whatever I did seems to be holding up, although it looks like I have the extension installed twice (probably the local dev version and the original one I installed). In the settings, the Raycast version shows two Spotify login buttons, while the dev version only has one. <img alt="Screenshot 2024-10-10 at 12 42 29 PM" width="1112" src="https://private-user-images.githubusercontent.com/25807/375522847-8dc9c084-8a75-4644-9592-08440ad2af2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzI1MDgsIm5iZiI6MTcyOTM3MjIwOCwicGF0aCI6Ii8yNTgwNy8zNzU1MjI4NDctOGRjOWMwODQtOGE3NS00NjQ0LTk1OTItMDg0NDBhZDJhZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIxMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjlmNGVlM2M1YTNjNWI3ZjdiN2I5MGViNGFkOGJlZmQ1NzFkNGE1NTZjYjQ0Y2FiMWYyOThhNmZmMmQ0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gfuUkjiz8ASvniacFp1ITfqRj1nDpYc4mN9B2YGpPp8"> <img alt="Screenshot 2024-10-10 at 12 42 32 PM" width="1112" src="https://private-user-images.githubusercontent.com/25807/375522877-21f8c836-04dc-42fb-9af2-f50ee494b4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzI1MDgsIm5iZiI6MTcyOTM3MjIwOCwicGF0aCI6Ii8yNTgwNy8zNzU1MjI4NzctMjFmOGM4MzYtMDRkYy00MmZiLTlhZjItZjUwZWU0OTRiNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIxMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzljMWE5YzBmZDExODZkMWFjODRiZWUxMjA0MzA0NTM1YTE3YmZkMWI1OGMwZmFkNzVmOTJmNTA2NTUyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XbBUOzh4v9yTwMmeotiSMgMupyr0gtm6BH-36WEgmNY">

I'd say go for the PR to fix this finally?

**Comment by elstgav** [comment]
Are there any updates on a fix for this? I just linked a number of related issues, this still seems to be an ongoing problem for many (including myself)

**Comment by DanClarke-io** [comment]
I am seeing this too - my company are using Zscaler as a internet filter, which could be what my issue is, but thought I should mention too.
