### ISSUE TITLE
[Todoist] Fails to fetch data and doesn't allow me to create tasks from Raycast 

### ISSUE THREAD

**Issue by pasindukp** [raycast/extensions#9999]
### Extension

https://raycast.com/doist/todoist

#### Error:

I used this extension quite a lot to create todoist tasks with a shortcut. But I've been getting the following error for a few days now and I can't create tasks from Raycast anymore. I've restarted the device, reinstalled the extension etc but it didn't help. 

AggregateError
    at Qn.from (/Users/pasindu/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:56:17861)
    at nt.<anonymous> (/Users/pasindu/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:59:8717)
    at nt.emit (node:events:514:28)
    at nt.emit (node:domain:488:12)
    at T3.<computed> (/Users/pasindu/.config/raycast/extensions/f9e9c663-3b16-4d34-a9b0-00f4af260acf/create-task.js:35:729)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:488:12)
```


### Steps To Reproduce

Use the raycast todoist shortcut to create a task
At the bottom left of the raycast window I get an error saying that it "Failed to fetch data" 

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by thomaslombart** [comment]
On which commands is this error happening?
